"use strict";var Eo=Object.create;var kn=Object.defineProperty;var ko=Object.getOwnPropertyDescriptor;var _o=Object.getOwnPropertyNames;var vo=Object.getPrototypeOf,xo=Object.prototype.hasOwnProperty;var Co=(e,n,t)=>n in e?kn(e,n,{enumerable:!0,configurable:!0,writable:!0,value:t}):e[n]=t;var Ao=(e,n,t,o)=>{if(n&&typeof n=="object"||typeof n=="function")for(let s of _o(n))!xo.call(e,s)&&s!==t&&kn(e,s,{get:()=>n[s],enumerable:!(o=ko(n,s))||o.enumerable});return e};var oe=(e,n,t)=>(t=e!=null?Eo(vo(e)):{},Ao(n||!e||!e.__esModule?kn(t,"default",{value:e,enumerable:!0}):t,e));var ve=(e,n,t)=>Co(e,typeof n!="symbol"?n+"":n,t);Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});const Po=require("node:path"),he=require("node:crypto"),c=require("electron"),Mo=require("node:fs"),Do=require("node:os"),Ae=require("node:child_process"),sn=require("child_process"),Oo=require("net"),Io=require("fs"),Ro=require("path"),Lo=require("os"),No=require("https");function te(e){const n=Object.create(null,{[Symbol.toStringTag]:{value:"Module"}});if(e){for(const t in e)if(t!=="default"){const o=Object.getOwnPropertyDescriptor(e,t);Object.defineProperty(n,t,o.get?o:{enumerable:!0,get:()=>e[t]})}}return n.default=e,Object.freeze(n)}const g=te(Po),h=te(Mo),Ke=te(Do),Go=te(Oo),M=te(Io),L=te(Ro),Fo=te(Lo),$o=te(No),D={claude:{name:"claude",displayName:"Claude",executableName:"claude",authCommand:"claude auth login",configPathKey:"claudePath",availableModels:["sonnet","haiku","opus"],defaultModel:"sonnet"},codex:{name:"codex",displayName:"Codex",executableName:"codex",authCommand:"codex auth",configPathKey:"codexPath",availableModels:["o4-mini","o3","gpt-4.1","gpt-4.1-mini","gpt-4.1-nano"],defaultModel:"o4-mini"},gemini:{name:"gemini",displayName:"Gemini",executableName:"gemini",authCommand:"gemini auth",configPathKey:"geminiPath",availableModels:["gemini-2.5-flash","gemini-2.5-pro","gemini-2.0-flash"],defaultModel:"gemini-2.5-flash"}},Fn={name:"local",displayName:"Built-in (Offline)",availableModels:["bonsai-1.7b","bonsai-4b","bonsai-8b","t5-grammar"],defaultModel:"bonsai-1.7b",modelRepoId:"Xenova/t5-base-grammar-correction"};({...Object.fromEntries(Object.entries(D).map(([e,n])=>[e,{name:n.name,displayName:n.displayName,availableModels:n.availableModels,defaultModel:n.defaultModel}]))});const zo=[{size:"1.7b",displayName:"Bonsai 1.7B (Default)",sizeMB:248},{size:"4b",displayName:"Bonsai 4B",sizeMB:572},{size:"8b",displayName:"Bonsai 8B",sizeMB:1150}],mn={"1.7b":"Bonsai-1.7B.gguf","4b":"Bonsai-4B.gguf","8b":"Bonsai-8B.gguf"},Uo={"1.7b":"prism-ml/Bonsai-1.7B-gguf","4b":"prism-ml/Bonsai-4B-gguf","8b":"prism-ml/Bonsai-8B-gguf"},$n="You are an English teacher helping a student. Read the following text and return a corrected version with proper grammar, spelling, and punctuation. Do not change correctly-spelled words to different words. Preserve the original vocabulary and meaning. Return only the corrected text, nothing else.",Q={ctxSize:4096,batchSize:512,nGpuLayers:99,healthPollMs:500,healthTimeoutPerAttemptMs:2e3,healthOverallTimeoutMs:6e4,shutdownGracePeriodMs:5e3,idleTimeoutMs:300*1e3},ht="int8",jo=[{variant:"q4f16",displayName:"Q4 F16 (Smallest)",sizeMB:210},{variant:"int8",displayName:"INT8 (Default)",sizeMB:250},{variant:"fp16",displayName:"FP16",sizeMB:496},{variant:"fp32",displayName:"FP32 (Largest)",sizeMB:963}],zn={q4f16:{encoder:"encoder_model_q4f16.onnx",decoder:"decoder_model_merged_q4f16.onnx"},int8:{encoder:"encoder_model_int8.onnx",decoder:"decoder_model_merged_int8.onnx"},fp16:{encoder:"encoder_model_fp16.onnx",decoder:"decoder_model_merged_fp16.onnx"},fp32:{encoder:"encoder_model.onnx",decoder:"decoder_model_merged.onnx"}},$={claudePath:"",codexPath:"",geminiPath:"",provider:"local",model:"bonsai-1.7b",localModelEngine:"bonsai",bonsaiModelSize:"1.7b",cliProvider:"claude",cliModel:"sonnet",timeoutSeconds:60,localHotkeyAccelerator:"CommandOrControl+E",cliHotkeyAccelerator:"CommandOrControl+Shift+E",undoHotkeyAccelerator:"CommandOrControl+Shift+Z",launchAtLogin:!1,historyLimit:50,developerMode:!1,language:"auto",soundFeedbackEnabled:!0,notifyOnSuccess:!1,clipboardOnlyMode:!1,tonePreset:"default",diffPreviewMode:"interactive",passivePreviewSeconds:5,autoPasteDelaySeconds:5,localModelVariant:"int8",localModelSpeed:"fast",firstRunComplete:!1,monitoringEnabled:!0,trafficLightPosition:"top-right",trafficLightInactivityMs:3e3,lineHotkeyAccelerator:"CommandOrControl+L",backgroundModelRefinement:!1,streakDates:[],dailyDigestEnabled:!0,settingsMode:"simple",monitoringAppFilter:"all",monitoringAppWhitelist:[],appToneOverrides:{},meetingModeEnabled:!0,meetingApps:["Zoom","Microsoft Teams","Google Meet","Webex","FaceTime"],suppressedSuggestions:{}},yt={default:"",casual:"Revise the following text for grammar and spelling. Use a casual, friendly, and conversational tone. Keep contractions, informal phrasing, and a relaxed style.",professional:"Revise for grammar, spelling, and punctuation. Use a polished, professional tone suitable for business communication.",academic:"Revise for grammar, spelling, and punctuation. Use a formal academic tone with precise vocabulary and clear structure.",slack:"Revise for grammar and spelling. Keep a concise, upbeat Slack-message tone. Preserve any emoji and informal abbreviations."},Pe="You are a grammar correction assistant. Fix grammar, spelling, and punctuation in the provided text. Do not change correctly-spelled words to different words. Return ONLY the corrected text, nothing else. Do not add explanations, notes, or markdown. Preserve the original meaning, tone, formatting, and vocabulary. If the text is already correct, return it as-is.",Bo=".ghostedit",Ho="config.json",Ko="history.json",Wo="prompt.txt",Vo="personal-dictionary.txt",qo=10;class Yo{constructor(){ve(this,"configDir");ve(this,"configPath");ve(this,"promptPath");ve(this,"cachedConfig",null);const n=Ke.homedir();this.configDir=g.join(n,Bo),this.configPath=g.join(this.configDir,Ho),this.promptPath=g.join(this.configDir,Wo)}ensureDefaults(){if(h.existsSync(this.configDir)||h.mkdirSync(this.configDir,{recursive:!0}),h.existsSync(this.configPath)||this.writeConfigFile($),!h.existsSync(this.promptPath)){const n=$.localModelEngine==="bonsai"?$n:Pe;h.writeFileSync(this.promptPath,n,"utf-8")}}load(){var n;if(this.cachedConfig)return{...this.cachedConfig};try{const t=h.readFileSync(this.configPath,"utf-8"),o=JSON.parse(t);o.hotkeyAccelerator&&!o.localHotkeyAccelerator&&(o.cliHotkeyAccelerator=o.hotkeyAccelerator,o.localHotkeyAccelerator=$.localHotkeyAccelerator,delete o.hotkeyAccelerator),o.cliProvider||o.provider&&o.provider!=="local"&&(o.cliProvider=o.provider,o.cliModel=o.model||((n=D[o.provider])==null?void 0:n.defaultModel)||"sonnet"),"showDiffPreview"in o&&!("diffPreviewMode"in o)&&(o.diffPreviewMode=o.showDiffPreview?"interactive":"none",delete o.showDiffPreview),o.localModelVariant==="fp32"&&(o.localModelVariant="int8"),"localModelEngine"in o||(o.localModelEngine="bonsai"),"bonsaiModelSize"in o||(o.bonsaiModelSize="1.7b"),o.model==="t5-grammar"&&o.provider==="local"&&(o.model="bonsai-1.7b");const s={...$,...o};return this.cachedConfig=s,{...s}}catch{return this.cachedConfig={...$},{...$}}}writeConfigFile(n){h.existsSync(this.configDir)||h.mkdirSync(this.configDir,{recursive:!0}),h.writeFileSync(this.configPath,JSON.stringify(n,null,2),"utf-8")}save(n){this.writeConfigFile(n),this.cachedConfig={...n}}update(n){const o={...this.load(),...n};return this.save(o),o}invalidateCache(){this.cachedConfig=null}loadSystemPrompt(){try{return h.readFileSync(this.promptPath,"utf-8").trim()||Pe}catch{return Pe}}saveSystemPrompt(n){h.existsSync(this.configDir)||h.mkdirSync(this.configDir,{recursive:!0}),h.writeFileSync(this.promptPath,n,"utf-8")}loadPersonalDictionary(){try{return h.readFileSync(this.personalDictionaryPath,"utf-8").split(`
`).map(t=>t.trim()).filter(Boolean)}catch{return[]}}savePersonalDictionary(n){h.existsSync(this.configDir)||h.mkdirSync(this.configDir,{recursive:!0}),h.writeFileSync(this.personalDictionaryPath,n.join(`
`),"utf-8")}get historyPath(){return g.join(this.configDir,Ko)}get personalDictionaryPath(){return g.join(this.configDir,Vo)}get configDirPath(){return this.configDir}}const m=new Yo;function wt(e,n,t){switch(e){case"claude":{const o=["-p",n,"--setting-sources","user","--tools",""];return t&&o.push("--model",t),o}case"codex":{const o=["exec","--skip-git-repo-check","--sandbox","read-only","-c","model_reasoning_effort='low'"];return t&&o.push("--model",t),o.push(n),o}case"gemini":{const o=["--prompt",n,"--output-format","text"];return t&&o.push("--model",t),o}default:throw new Error(`Unknown provider: ${e}`)}}function Zo(e){const n=Ke.homedir(),t=D[e].executableName,o=[];if(process.platform==="win32"){const r=process.env.APPDATA||g.join(n,"AppData","Roaming"),a=process.env.LOCALAPPDATA||g.join(n,"AppData","Local");o.push(g.join(r,"npm",`${t}.cmd`),g.join(a,"Programs",t,`${t}.exe`),g.join(n,"scoop","shims",`${t}.exe`))}else o.push(g.join(n,".local","bin",t),`/opt/homebrew/bin/${t}`,`/usr/local/bin/${t}`,`/usr/bin/${t}`,g.join(n,"bin",t));const s=process.env.PATH||"",i=process.platform==="win32"?";":":";for(const r of s.split(i)){if(!r)continue;const a=process.platform==="win32"?".cmd":"",l=g.join(r,`${t}${a}`);o.includes(l)||o.push(l)}return o}function gn(e,n){if(n&&h.existsSync(n))return n;for(const t of Zo(e))try{if(h.existsSync(t))return t}catch{}return null}function bt(){const e=Ke.homedir(),n=process.platform==="win32"?";":":",t=[];if(process.platform==="win32"){const s=process.env.APPDATA||g.join(e,"AppData","Roaming");t.push(g.join(s,"npm"))}else t.push(g.join(e,".local","bin"),"/opt/homebrew/bin","/usr/local/bin",g.join(e,"bin"));const o=process.env.PATH||"";return[...t,o].join(n)}function Xo(e,n){const t=`${e}
${n}`.toLowerCase();return["failed to authenticate","authentication_error","token has expired","oauth token","api error: 401","unauthorized","invalid credentials","not logged in","please log in"].some(s=>t.includes(s))}const Ee=g.join(Ke.homedir(),".ghostedit","device-cache.json");let X=null;function Jo(){try{if(!h.existsSync(Ee))return null;const e=JSON.parse(h.readFileSync(Ee,"utf-8"));return e.appVersion!==c.app.getVersion()?null:{device:e.device,runtime:e.runtime,label:e.label}}catch{return null}}function _n(e){try{const n=g.dirname(Ee);h.existsSync(n)||h.mkdirSync(n,{recursive:!0});const t={appVersion:c.app.getVersion(),...e};h.writeFileSync(Ee,JSON.stringify(t,null,2))}catch{}}function Qo(){X=null;try{h.existsSync(Ee)&&h.unlinkSync(Ee)}catch{}}function es(){const e=process.platform,n=process.arch,t={device:"cpu",runtime:"node",label:"CPU (Node)"};return e==="win32"?[{device:"dml",runtime:"node",label:"DirectML (GPU)"},t]:e==="linux"&&n==="x64"?[{device:"cuda",runtime:"node",label:"CUDA (GPU)"},t]:[t]}async function ns(e,n,t,o){try{const{pipeline:s}=await import("@huggingface/transformers"),i={...o,device:e};return await s("text2text-generation",n,i)}catch(s){return console.warn(`[GhostEdit] Device probe failed for "${e}":`,s.message),null}}async function ts(e,n,t){if(X)return{selection:X,pipeline:null};const o=Jo();if(o)return X=o,console.log(`[GhostEdit] Using cached device: ${o.label}`),{selection:o,pipeline:null};const s=es();for(const r of s){if(r.runtime==="node"&&(r.device==="dml"||r.device==="cuda")){console.log(`[GhostEdit] Probing device: ${r.label}...`);const a=await ns(r.device,e,n,t);if(a)return X=r,_n(r),console.log(`[GhostEdit] Selected device: ${r.label}`),{selection:r,pipeline:a};continue}return X=r,_n(r),console.log(`[GhostEdit] Selected device: ${r.label}`),{selection:r,pipeline:null}}const i={device:"cpu",runtime:"node",label:"CPU (Node)"};return X=i,_n(i),{selection:i,pipeline:null}}function Un(){return X}let ee=null,Ve=null;const os=500;function We(){if(ee===null){const e=m.historyPath;try{const n=h.readFileSync(e,"utf-8");ee=JSON.parse(n)}catch{ee=[]}}return ee}function St(){Ve&&clearTimeout(Ve),Ve=setTimeout(()=>{if(Ve=null,ee===null)return;const e=m.historyPath;h.promises.writeFile(e,JSON.stringify(ee,null,2),"utf-8").catch(n=>{console.error("[GhostEdit] Failed to persist history:",n)})},os)}function nt(){return We()}function xe(e,n){const t=We();t.push(e);const o=n??m.load().historyLimit;t.length>o&&(ee=t.slice(t.length-o)),St()}function ss(){ee=[],St()}function is(){const e=We();for(let n=e.length-1;n>=0;n--)if(e[n].succeeded)return e[n];return null}function Tt(e){const n=new Date().toISOString().split("T")[0],t=new Set(e);t.add(n);const o=[...t].sort().reverse();let s=0;const i=new Date(n);for(let a=0;a<o.length;a++){const l=new Date(i);l.setDate(l.getDate()-a);const d=l.toISOString().split("T")[0];if(o[a]===d)s++;else break}return{streakDates:o.slice(0,90),streakCount:s}}function rs(){const e=We(),n=new Date().toISOString().split("T")[0],t=e.filter(a=>a.timestamp.startsWith(n));if(t.length===0)return{count:0,spellingFixes:0,grammarFixes:0,successRate:0};const o=t.filter(a=>a.succeeded).length,s=Math.round(o/t.length*100);let i=0,r=0;for(const a of t){if(!a.succeeded||!a.originalText||!a.generatedText)continue;const l=a.originalText.split(/\s+/),d=a.generatedText.split(/\s+/);l.length===d.length?i++:r++}return{count:t.length,spellingFixes:i,grammarFixes:r,successRate:s}}function as(){const e=We(),n=e.filter(a=>a.succeeded),t=e.filter(a=>!a.succeeded),o=n.reduce((a,l)=>a+l.durationMilliseconds,0),s=n.reduce((a,l)=>a+(l.originalText?l.originalText.split(/\s+/).length:0),0),i={};for(const a of e){const l=a.provider;i[l]=(i[l]||0)+1}const r={};for(const a of e){const l=a.timestamp.split("T")[0];r[l]=(r[l]||0)+1}return{totalCorrections:e.length,successfulCorrections:n.length,failedCorrections:t.length,successRate:e.length>0?Math.round(n.length/e.length*100):0,totalDurationMs:o,avgDurationMs:n.length>0?Math.round(o/n.length):0,totalWordsProcessed:s,correctionsByProvider:i,correctionsByDate:r}}let Et=null,qe=null;function ls(e){qe=e.onUpdateAvailable;try{const{autoUpdater:n}=require("electron-updater");n.autoDownload=!1,n.autoInstallOnAppQuit=!1,n.on("update-available",t=>{Et=t.version,qe==null||qe(t.version),console.log(`[GhostEdit] Update available: v${t.version}`)}),n.on("error",t=>{console.warn("[GhostEdit] Auto-updater error:",t.message)}),n.checkForUpdates().catch(t=>{console.warn("[GhostEdit] Update check failed:",t.message)})}catch(n){console.warn("[GhostEdit] electron-updater not available:",n.message)}}function tt(){return Et}function cs(){try{const{autoUpdater:e}=require("electron-updater");e.downloadUpdate().then(()=>{e.quitAndInstall(!1,!0)})}catch(e){console.error("[GhostEdit] Failed to download update:",e.message)}}let P=null,rn="idle",an=null,Me=0,Ue=null;function ds(e){return c.app.isPackaged?g.join(process.resourcesPath,e):g.join(c.app.getAppPath(),"assets",e)}const us={green:{b:94,g:197,r:34,a:255},yellow:{b:8,g:179,r:234,a:255},red:{b:68,g:68,r:239,a:255}},Ye={b:30,g:30,r:30,a:255};function ps(e,n,t,o){const s=us[o],i=35,r=35,a=5,l=6;for(let d=r-l;d<=r+l;d++)for(let u=i-l;u<=i+l;u++){if(u<0||u>=n||d<0||d>=t)continue;const p=Math.sqrt((u-i)**2+(d-r)**2);if(p<=a){const b=(d*n+u)*4;e[b]=s.b,e[b+1]=s.g,e[b+2]=s.r,e[b+3]=s.a}else if(p<=l){const b=(d*n+u)*4;e[b]=Ye.b,e[b+1]=Ye.g,e[b+2]=Ye.r,e[b+3]=Ye.a}}}const ge=new Map,fs=8;function kt(e,n){const t=`${e}-${n??"none"}`,o=ge.get(t);if(o)return o;const s=e==="idle"?"MenuBarIconIdle.png":"MenuBarIconProcessing.png",i=c.nativeImage.createFromPath(ds(s)),r=i.getSize(),a=Buffer.from(i.toBitmap());n!==null&&ps(a,r.width,r.height,n);let l=c.nativeImage.createFromBitmap(a,{width:r.width,height:r.height});if(process.platform==="darwin"){const d=c.nativeImage.createEmpty();d.addRepresentation({buffer:l.toPNG(),width:22,height:22,scaleFactor:2}),l=d}else process.platform==="win32"&&(l=l.resize({width:32,height:32}));if(ge.size>=fs){const d=ge.keys().next().value;d!==void 0&&ge.delete(d)}return ge.set(t,l),l}function _t(){if(!P)return;const e=rn==="processing"?null:an;P.setImage(kt(rn,e))}function ln(e){!P||rn===e||(rn=e,_t())}function cn(e){an!==e&&(an=e,_t())}function ms(){return P?P.getBounds():null}function vt(e){Me=e,Ue&&dn(Ue)}function gs(e){Ue=e;const n=kt("idle",null);return P=new c.Tray(n),P.setToolTip("GhostEdit"),process.platform!=="darwin"&&P.on("click",()=>{P==null||P.popUpContextMenu()}),dn(e),P}function dn(e){if(!P)return;Ue=e;const n=m.load(),t=D[n.cliProvider],s=(t?gn(t.name,n[t.configPathKey]||void 0):null)?`CLI (${t==null?void 0:t.displayName}): Found`:`CLI (${t==null?void 0:t.displayName}): Not found`,i=[];if(n.developerMode){const u=Un();u&&i.push({label:`Inference: ${u.label}`,enabled:!1})}const r=[];n.monitoringEnabled&&(Me>0?r.push({label:`${Me} issue${Me===1?"":"s"} found...`,click:()=>{var u;return(u=e.onShowSuggestions)==null?void 0:u.call(e)}}):r.push({label:"No issues",enabled:!1}),r.push({type:"separator"}));const{streakCount:a}=Tt(n.streakDates??[]),l=a>=3?`🔥 ${a}-day streak`:a===1?"Used today":a===2?"2-day streak":null,d=c.Menu.buildFromTemplate([{label:"GhostEdit",enabled:!1},...l?[{label:l,enabled:!1}]:[],{type:"separator"},...r,{label:`Local: Built-in (${n.localModelVariant??"fp32"})`,enabled:!1},{label:`CLI: ${(t==null?void 0:t.displayName)??"None"} / ${n.cliModel}`,enabled:!1},{label:s,enabled:!1},...i,{type:"separator"},{label:`Correct (Local) (${vn(n.localHotkeyAccelerator)})`,click:e.onCorrectLocal},{label:`Correct (${(t==null?void 0:t.displayName)??"CLI"}) (${vn(n.cliHotkeyAccelerator)})`,click:e.onCorrectCLI},{type:"separator"},{label:`Undo Last Correction (${vn(n.undoHotkeyAccelerator)})`,click:e.onUndoLastCorrection},...hs(e),{type:"separator"},{label:"Settings...",click:e.onOpenSettings},{label:"History...",click:e.onOpenHistory},{type:"separator"},...tt()?[{label:`Update available (v${tt()})`,click:()=>{var u;return(u=e.onDownloadUpdate)==null?void 0:u.call(e)}}]:[],{label:"Quit GhostEdit",click:()=>c.app.quit()}]);P.setContextMenu(d)}function hs(e){var o;const n=((o=e.getRecentCorrections)==null?void 0:o.call(e))??[];return n.length===0?[]:[{label:"Recent Corrections",submenu:n.map(s=>({label:s.corrected.length>40?s.corrected.slice(0,40)+"...":s.corrected,click:()=>c.clipboard.writeText(s.corrected)}))}]}function vn(e){return e?e.replace("CommandOrControl",process.platform==="darwin"?"⌘":"Ctrl").replace("Shift",process.platform==="darwin"?"⇧":"Shift").replace("Alt",process.platform==="darwin"?"⌥":"Alt").replace(/\+/g,process.platform==="darwin"?"":"+"):""}function ys(){P&&(P.destroy(),P=null),Ue=null,an=null,Me=0,ge.clear()}let xt=null,Ct=null,At=null,Pt=null;function Mt(e,n,t,o){const s=m.load(),i=s.localHotkeyAccelerator||$.localHotkeyAccelerator,r=s.cliHotkeyAccelerator||$.cliHotkeyAccelerator,a=s.undoHotkeyAccelerator||$.undoHotkeyAccelerator,l=s.lineHotkeyAccelerator||$.lineHotkeyAccelerator;i===r&&console.warn("[GhostEdit] Local and CLI hotkeys are the same — only local will be registered"),Ze(i,e,"local"),i!==r&&Ze(r,n,"cli"),a&&a!==i&&a!==r&&Ze(a,t,"undo"),o&&l&&l!==i&&l!==r&&l!==a&&Ze(l,o,"line")}function Ze(e,n,t){if(!e){console.warn(`[GhostEdit] No ${t} hotkey accelerator configured`);return}try{c.globalShortcut.register(e,n)?t==="local"?xt=e:t==="cli"?Ct=e:t==="undo"?At=e:t==="line"&&(Pt=e):console.error(`[GhostEdit] Failed to register ${t} global shortcut: ${e}`)}catch(o){console.error(`[GhostEdit] Error registering ${t} shortcut "${e}":`,o)}}function ws(e,n,t,o){Dt(),Mt(e,n,t,o)}function Dt(){c.globalShortcut.unregisterAll(),xt=null,Ct=null,At=null,Pt=null}const f={CORRECT_TEXT:"correct-text",CORRECT_TEXT_STREAMING:"correct-text-streaming",STREAMING_CHUNK:"streaming-chunk",STREAMING_DONE:"streaming-done",STREAMING_ERROR:"streaming-error",GET_CONFIG:"get-config",SAVE_CONFIG:"save-config",GET_HISTORY:"get-history",CLEAR_HISTORY:"clear-history",EXPORT_HISTORY:"export-history",OPEN_WINDOW:"open-window",HUD_SHOW:"hud-show",HUD_HIDE:"hud-hide",GET_CLI_STATUS:"get-cli-status",ACCEPT_CORRECTION:"accept-correction",REJECT_CORRECTION:"reject-correction",REGENERATE_CORRECTION:"regenerate-correction",GET_LOCAL_MODEL_STATUS:"get-local-model-status",DOWNLOAD_MODEL_VARIANT:"download-model-variant",DOWNLOAD_VARIANT_PROGRESS:"download-variant-progress",DOWNLOAD_VARIANT_ERROR:"download-variant-error",SET_PREVIEW_ORIGINAL:"set-preview-original",SET_PREVIEW_CONFIG:"set-preview-config",INFERENCE_COMMAND:"inference:command",INFERENCE_RESULT:"inference:result",GET_INFERENCE_DEVICE:"get-inference-device",GET_ERROR_LOG:"get-error-log",GET_SYSTEM_PROMPT:"get-system-prompt",SAVE_SYSTEM_PROMPT:"save-system-prompt",GET_PERSONAL_DICTIONARY:"get-personal-dictionary",SAVE_PERSONAL_DICTIONARY:"save-personal-dictionary",GET_USAGE_STATS:"get-usage-stats",SUGGESTIONS_UPDATE:"suggestions-update",APPLY_FIX:"apply-fix",APPLY_ALL_FIXES:"apply-all-fixes",CHECK_ACCESSIBILITY:"check-accessibility",CORRECT_INLINE:"correct-inline",EXPLAIN_DIFF:"explain-diff",RE_CORRECT:"re-correct",DISMISS_SUGGESTION:"dismiss-suggestion",GET_BONSAI_STATUS:"get-bonsai-status",DOWNLOAD_BONSAI_MODEL:"download-bonsai-model",DOWNLOAD_BONSAI_PROGRESS:"download-bonsai-progress",DOWNLOAD_BONSAI_ERROR:"download-bonsai-error"};function Ot(e){let n=e;n=n.replace(/^—+\s*/g,"").replace(/\s*—+$/g,"");const t=n.split(`
`);let o=0;for(;o<t.length&&t[o].trim()==="";)o++;let s=t.length-1;for(;s>o&&t[s].trim()==="";)s--;return t.slice(o,s+1).join(`
`).trimEnd()}function It(e,n,t,o){return Xo(t,o)?{type:"authentication-required",message:`${D[e].displayName} requires authentication. Run: ${D[e].authCommand}`,provider:e}:{type:"process-failed",message:`${D[e].displayName} exited with code ${n}`,provider:e,exitCode:n,stderr:o}}async function bs(e,n,t){if(t.provider==="local")throw{type:"launch-failed",message:"Local provider should use local-model-runner"};const o=t.provider,s=t[D[o].configPathKey],i=gn(o,s||void 0);if(!i)throw{type:"cli-not-found",message:`${D[o].displayName} CLI not found. Install it or set the path in settings.`,provider:o};const r=e?`${e}

Text to correct:
${n}`:n,a=t.model||void 0,l=wt(o,r,a),d=Date.now();return new Promise((u,p)=>{var y,A;const b={...process.env,PATH:bt()};delete b.CLAUDE_CODE,delete b.CLAUDECODE;const S=Ae.spawn(i,l,{env:b,stdio:["ignore","pipe","pipe"],timeout:t.timeoutSeconds*1e3}),E=[],x=[];(y=S.stdout)==null||y.on("data",v=>{E.push(v)}),(A=S.stderr)==null||A.on("data",v=>{x.push(v)}),S.on("error",v=>{p({type:"launch-failed",message:`Failed to launch ${D[o].displayName}: ${v.message}`,provider:o})}),S.on("close",v=>{const k=Date.now()-d,H=Buffer.concat(E).toString(),me=Buffer.concat(x).toString();if(v===null){p({type:"timed-out",message:`${D[o].displayName} timed out after ${t.timeoutSeconds}s`,provider:o});return}if(v!==0){p(It(o,v,H,me));return}const Z=Ot(H);if(!Z){p({type:"empty-response",message:`${D[o].displayName} returned an empty response`,provider:o});return}u({text:Z,durationMs:k})});const w=setTimeout(()=>{S.exitCode===null&&(S.kill("SIGTERM"),setTimeout(()=>{S.exitCode===null&&S.kill("SIGKILL")},2e3))},t.timeoutSeconds*1e3);S.once("close",()=>{clearTimeout(w),S.removeAllListeners()})})}async function Ss(e,n,t,o){if(o.provider==="local")throw{type:"launch-failed",message:"Local provider should use local-model-runner"};const s=o.provider,i=o[D[s].configPathKey],r=gn(s,i||void 0);if(!r)throw{type:"cli-not-found",message:`${D[s].displayName} CLI not found.`,provider:s};const a=e?`${e}

Text to correct:
${n}`:n,l=o.model||void 0,d=wt(s,a,l),u=Date.now();return new Promise((p,b)=>{var A,v;const S={...process.env,PATH:bt()};delete S.CLAUDE_CODE,delete S.CLAUDECODE;const E=Ae.spawn(r,d,{env:S,stdio:["ignore","pipe","pipe"]}),x=[],w=[];(A=E.stdout)==null||A.on("data",k=>{const H=k.toString();x.push(k),t(H)}),(v=E.stderr)==null||v.on("data",k=>{w.push(k)}),E.on("error",k=>{b({type:"launch-failed",message:k.message,provider:s})}),E.on("close",k=>{const H=Date.now()-u,me=Buffer.concat(x).toString(),Z=Buffer.concat(w).toString();if(k===null||k!==0){b(k===null?{type:"timed-out",message:`${D[s].displayName} timed out`,provider:s}:It(s,k,me,Z));return}const _e=Ot(me);if(!_e){b({type:"empty-response",message:"Empty response",provider:s});return}p({text:_e,durationMs:H})});const y=setTimeout(()=>{E.exitCode===null&&E.kill("SIGTERM")},o.timeoutSeconds*1e3);E.once("close",()=>{clearTimeout(y),E.removeAllListeners()})})}let F=null,ie=null,re=null;const Ts=300*1e3;let Xe=null;function Rt(){Xe&&clearTimeout(Xe),Xe=setTimeout(()=>{F&&(console.log("[GhostEdit] Unloading idle model to free memory"),F=null,ie=null,re=null),Xe=null},Ts)}const ke="Xenova/t5-base-grammar-correction",je="onnx",Es=["config.json","tokenizer.json","tokenizer_config.json","generation_config.json"];function hn(){return c.app.isPackaged?g.join(process.resourcesPath,"models"):g.join(c.app.getAppPath(),"resources","models")}function jn(){return g.join(Ke.homedir(),".ghostedit","models")}function Lt(e){const n=jn(),t=g.join(n,ke,je),o=zn[e];return h.existsSync(g.join(t,o.encoder))&&h.existsSync(g.join(t,o.decoder))?n:hn()}function ks(e){const n=zn[e],t=g.join(hn(),ke,je);if(h.existsSync(g.join(t,n.encoder))&&h.existsSync(g.join(t,n.decoder)))return!0;const o=g.join(jn(),ke,je);return!!(h.existsSync(g.join(o,n.encoder))&&h.existsSync(g.join(o,n.decoder)))}function _s(e){const n=zn[e],t=g.join(hn(),ke,je);return h.existsSync(g.join(t,n.encoder))&&h.existsSync(g.join(t,n.decoder))}let Ce=null,Dn=0;const vs=3e4;function xs(){const e=Date.now();return Ce&&e-Dn<vs||(Ce=jo.map(n=>({variant:n.variant,displayName:n.displayName,sizeMB:n.sizeMB,available:ks(n.variant),bundled:_s(n.variant)})),Dn=e),Ce}function Cs(){Ce=null,Dn=0}function As(){const n=m.load().localModelVariant??ht,t=xs(),o=t.find(s=>s.variant===n);return{ready:(o==null?void 0:o.available)??!1,activeVariant:n,variants:t}}async function Ps(e,n){const{pipeline:t}=await import("@huggingface/transformers"),s={cache_dir:Lt(e),local_files_only:!0};return e!=="fp32"&&(s.dtype=e),n&&(s.device=n),t("text2text-generation",Fn.modelRepoId,s)}async function Bn(){const n=m.load().localModelVariant??ht;let t=Un();if(!t){const s=Lt(n),i={cache_dir:s,local_files_only:!0};n!=="fp32"&&(i.dtype=n);try{const{selection:r,pipeline:a}=await ts(Fn.modelRepoId,s,i);if(t=r,a&&r.runtime==="node")return Ds(a,n,r.device),a}catch{}}const o=(t==null?void 0:t.runtime)==="node"&&t.device!=="cpu"?t.device:void 0;if(F&&(ie!==n||re!==(o??null))&&(F=null,ie=null,re=null),F)return F;ie=n,re=o??null,F=Ps(n,o);try{return await F}catch(s){throw F=null,ie=null,re=null,s}}function Ms(){F=null,ie=null,re=null}function Ds(e,n,t){F=Promise.resolve(e),ie=n,re=t}async function Os(e,n){const{pipeline:t}=await import("@huggingface/transformers"),o=jn(),s=g.join(o,ke);h.mkdirSync(g.join(s,je),{recursive:!0});const i=g.join(hn(),ke);for(const a of Es){const l=g.join(s,a),d=g.join(i,a);!h.existsSync(l)&&h.existsSync(d)&&h.copyFileSync(d,l)}const r={cache_dir:o,local_files_only:!1,progress_callback:a=>{(a==null?void 0:a.progress)!=null&&n&&n(Math.round(a.progress))}};e!=="fp32"&&(r.dtype=e),await t("text2text-generation",Fn.modelRepoId,r),Cs()}function Is(){m.load().provider==="local"&&Bn().catch(n=>{console.warn("[GhostEdit] Model pre-warm failed:",n.message)})}async function Nt(e,n){var u;const t=Date.now(),o=m.load(),s=await Bn(),i=`grammar: ${n}`,r=Math.min(n.length*2,512),a=o.localModelSpeed==="quality"?{num_beams:4,early_stopping:!0}:{num_beams:1},l=await s(i,{max_new_tokens:r,no_repeat_ngram_size:3,repetition_penalty:1.2,...a}),d=Array.isArray(l)?((u=l[0])==null?void 0:u.generated_text)??"":String(l);return Rt(),{text:d.trim(),durationMs:Date.now()-t}}async function Rs(e,n,t){const o=m.load(),s=Date.now(),i=await Bn(),r=`grammar: ${n}`,a=Math.min(n.length*2,512),l=o.localModelSpeed==="quality"?{num_beams:4,early_stopping:!0}:{num_beams:1};try{const{TextStreamer:d}=await import("@huggingface/transformers");let u="";const p=new d(i.tokenizer,{skip_prompt:!0,callback_function:b=>{u+=b,t(b)}});return await i(r,{max_new_tokens:a,no_repeat_ngram_size:3,repetition_penalty:1.2,...l,streamer:p}),Rt(),{text:u.trim(),durationMs:Date.now()-s}}catch{const d=await Nt(e,n);return t(d.text),d}}function Gt(){return c.app.isPackaged?L.join(process.resourcesPath,"models","bonsai"):L.join(c.app.getAppPath(),"resources","models","bonsai")}function Hn(){return L.join(c.app.getPath("home"),".ghostedit","models","bonsai")}function Ls(e){const n=mn[e],t=L.join(Hn(),n);if(M.existsSync(t))return t;const o=L.join(Gt(),n);return M.existsSync(o)?o:null}let Qe=null,On=0;const Ns=3e4;function ot(){const e=Date.now();if(Qe&&e-On<Ns)return Qe;const n=Gt(),t=Hn(),o=zo.map(s=>{const i=mn[s.size],r=L.join(n,i),a=L.join(t,i),l=M.existsSync(r),d=M.existsSync(a);return{size:s.size,displayName:s.displayName,sizeMB:s.sizeMB,available:l||d,bundled:l}});return Qe=o,On=e,o}function Gs(){Qe=null,On=0}function Fs(e){const n=Uo[e],t=mn[e];return`https://huggingface.co/${n}/resolve/main/${t}`}async function $s(e,n){const t=Fs(e),o=Hn(),s=mn[e],i=L.join(o,s),r=i+".partial";M.mkdirSync(o,{recursive:!0}),await new Promise((a,l)=>{const d=(u,p)=>{if(p>5){l(new Error("Too many redirects"));return}(u.startsWith("https")?$o:require("http")).get(u,S=>{if(S.statusCode>=300&&S.statusCode<400&&S.headers.location){d(S.headers.location,p+1);return}if(S.statusCode!==200){l(new Error(`Download failed: HTTP ${S.statusCode}`));return}const E=parseInt(S.headers["content-length"]||"0",10);let x=0;const w=M.createWriteStream(r);S.on("data",y=>{x+=y.length,E>0&&n&&n(Math.round(x/E*100))}),S.pipe(w),w.on("finish",()=>{w.close(),M.renameSync(r,i),Gs(),a()}),w.on("error",y=>{try{M.unlinkSync(r)}catch{}l(y)}),S.on("error",y=>{try{M.unlinkSync(r)}catch{}l(y)})}).on("error",l)};d(t,0)})}let O=null,V=null,le=null,ce=!1;function yn(){return L.join(c.app.getPath("home"),".ghostedit")}function Kn(){return L.join(yn(),"llama-server.pid")}function Ft(){return L.join(yn(),"llama-server.log")}function zs(){const e=process.platform==="win32"?"llama-server.exe":"llama-server",n=`${process.platform}-${process.arch}`;return c.app.isPackaged?L.join(process.resourcesPath,"bin",n,e):L.join(c.app.getAppPath(),"resources","bin",n,e)}function Us(){return new Promise((e,n)=>{const t=Go.createServer();t.listen(0,"127.0.0.1",()=>{const o=t.address();if(o&&typeof o=="object"){const s=o.port;t.close(()=>e(s))}else t.close(()=>n(new Error("Failed to allocate port")))}),t.on("error",n)})}async function js(e){const n=Date.now();for(;Date.now()-n<Q.healthOverallTimeoutMs;){try{const t=new AbortController,o=setTimeout(()=>t.abort(),Q.healthTimeoutPerAttemptMs),s=await fetch(`http://127.0.0.1:${e}/health`,{signal:t.signal});if(clearTimeout(o),s.ok)return}catch{}if(O&&O.exitCode!==null)throw new Error(`llama-server exited during startup (code ${O.exitCode}). Check ${Ft()}`);await new Promise(t=>setTimeout(t,Q.healthPollMs))}throw new Error(`llama-server health check timed out after ${Q.healthOverallTimeoutMs/1e3}s`)}function Bs(e,n,t){const o={pid:e,port:n,modelPath:t,startedAt:new Date().toISOString()};M.mkdirSync(yn(),{recursive:!0}),M.writeFileSync(Kn(),JSON.stringify(o,null,2))}function fe(){try{M.unlinkSync(Kn())}catch{}}function Hs(){try{const e=M.readFileSync(Kn(),"utf-8"),n=JSON.parse(e);if(n!=null&&n.pid)try{process.kill(n.pid,"SIGTERM")}catch{}}catch{}fe()}async function Ks(e){Hs();const n=zs();if(!M.existsSync(n))throw new Error(`llama-server binary not found at ${n}`);const t=Ls(e);if(!t)throw new Error(`Bonsai ${e} model not found. Download it first.`);const o=await Us(),s=Ft();M.mkdirSync(yn(),{recursive:!0});const i=M.openSync(s,"w"),r=["-m",t,"--host","127.0.0.1","--port",String(o),"--ctx-size",String(Q.ctxSize),"--threads",String(Fo.cpus().length),"--batch-size",String(Q.batchSize),"-ngl",String(Q.nGpuLayers)],a=sn.spawn(n,r,{stdio:["ignore",i,i]});M.closeSync(i),a.on("error",l=>{console.error("[GhostEdit] llama-server spawn error:",l.message),O=null,ce=!1,le=null,V=null,fe()}),a.on("exit",l=>{console.warn(`[GhostEdit] llama-server exited (code ${l})`),O=null,ce=!1,le=null,V=null,fe()}),O=a,V=o,le=e,Bs(a.pid,o,t),await js(o),ce=!0}async function $t(){if(!O){fe();return}const e=O;if(O=null,ce=!1,le=null,V=null,process.platform==="win32")try{sn.spawn("taskkill",["/pid",String(e.pid),"/f","/t"])}catch{}else try{e.kill("SIGTERM")}catch{}if(!await new Promise(t=>{const o=setTimeout(()=>t(!1),Q.shutdownGracePeriodMs);e.on("exit",()=>{clearTimeout(o),t(!0)}),e.exitCode!==null&&(clearTimeout(o),t(!0))}))try{process.platform==="win32"?sn.spawn("taskkill",["/pid",String(e.pid),"/f","/t"]):e.kill("SIGKILL")}catch{}fe()}async function Wn(e){return O&&ce&&le===e&&V||(O&&await $t(),await Ks(e)),V}function st(){return{running:O!==null&&O.exitCode===null,port:V,healthy:ce,modelSize:le}}function Ws(){if(!O){fe();return}try{process.platform==="win32"?sn.spawn("taskkill",["/pid",String(O.pid),"/f","/t"]):O.kill("SIGTERM")}catch{}O=null,ce=!1,le=null,V=null,fe()}function Vs(e){return e.replace(/<tool_call>[\s\S]*?<\/tool_call>/g,"").trim()}function zt(e){return e===Pe?$n:e}async function qs(e,n){var l,d,u;const t=m.load(),o=await Wn(t.bonsaiModelSize),s=zt(e),i=Date.now(),r=new AbortController,a=setTimeout(()=>r.abort(),t.timeoutSeconds*1e3);try{const p=await fetch(`http://127.0.0.1:${o}/v1/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"bonsai",messages:[{role:"system",content:s},{role:"user",content:n}],stream:!1,temperature:.1,max_tokens:Math.min(n.length*3,2048)}),signal:r.signal});if(!p.ok){const x=await p.text().catch(()=>"");throw new Error(`llama-server returned HTTP ${p.status}: ${x}`)}const b=await p.json(),S=((u=(d=(l=b==null?void 0:b.choices)==null?void 0:l[0])==null?void 0:d.message)==null?void 0:u.content)??"",E=Vs(S);if(!E)throw new Error("Empty response from bonsai model");return{text:E,durationMs:Date.now()-i}}finally{clearTimeout(a)}}async function Ys(e,n,t){var d,u,p,b;const o=m.load(),s=await Wn(o.bonsaiModelSize),i=zt(e),r=Date.now(),a=new AbortController,l=setTimeout(()=>a.abort(),o.timeoutSeconds*1e3);try{const S=await fetch(`http://127.0.0.1:${s}/v1/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"bonsai",messages:[{role:"system",content:i},{role:"user",content:n}],stream:!0,temperature:.1,max_tokens:Math.min(n.length*3,2048)}),signal:a.signal});if(!S.ok){const v=await S.text().catch(()=>"");throw new Error(`llama-server returned HTTP ${S.status}: ${v}`)}let E="";const x=(d=S.body)==null?void 0:d.getReader();if(!x)throw new Error("No response body stream");const w=new TextDecoder;let y="";for(;;){const{done:v,value:k}=await x.read();if(v)break;y+=w.decode(k,{stream:!0});const H=y.split(`
`);y=H.pop()??"";for(const me of H){const Z=me.trim();if(!Z||!Z.startsWith("data: "))continue;const _e=Z.slice(6);if(_e==="[DONE]")break;try{const Tn=JSON.parse(_e),et=(b=(p=(u=Tn==null?void 0:Tn.choices)==null?void 0:u[0])==null?void 0:p.delta)==null?void 0:b.content;if(et){const En=et.replace(/<tool_call>/g,"").replace(/<\/tool_call>/g,"");En&&(E+=En,t(En))}}catch{}}}const A=E.trim();if(!A)throw new Error("Empty response from bonsai model");return{text:A,durationMs:Date.now()-r}}finally{clearTimeout(l)}}async function ye(e,n,t){return t.provider==="local"?t.localModelEngine==="t5"?Nt(e,n):qs(e,n):bs(e,n,t)}async function Zs(e,n,t,o){return o.provider==="local"?o.localModelEngine==="t5"?Rs(e,n,t):Ys(e,n,t):Ss(e,n,t,o)}const en=[];function Ut(e,n){en.push({id:he.randomUUID(),timestamp:new Date().toISOString(),message:e,provider:n}),en.length>qo&&en.shift()}function Xs(){return[...en]}const Js=`ack
addon
addons
adtech
adware
airbnb
ajax
algo
algos
algorand
alphanumeric
analytics
android
ansible
antipattern
antipatterns
apache
api
apis
applet
applets
architected
arduino
arg
args
async
atlassian
auth
autocompletion
autocomplete
autofill
autogenerate
autogenerated
autoscale
autoscaling
aws
backend
backends
backfill
backfilled
backlog
backlogs
backport
backported
backporting
backpressure
backtick
backticks
bandwith
barebone
baremetal
basename
bigint
bigquery
bioinformatics
bitbucket
bitcoin
bitfield
bitmap
bitrate
bitwise
blockchain
blog
blogging
blogs
bluetooth
boolean
booleans
bootloader
botnet
breakpoint
breakpoints
broadband
browsable
browserify
bytecode
cacheability
cacheable
caching
captcha
cdn
chatbot
chatbots
chatroom
checkbox
checkboxes
checksum
checksums
ci
cli
clickable
clickjacking
clipboard
cloudflare
cloudfront
cloudwatch
cmake
cname
coalesce
codebase
codebases
codec
codegen
codepoint
codepoints
colocation
colocated
concat
concurrency
config
configs
containerization
containerize
containerized
cors
couchdb
cpu
cpus
cron
cronjob
crowdsource
crowdsourced
cryptocurrency
cryptographic
css
csv
cuda
daemon
daemons
darknet
dataflow
drawback
drawbacks
dataframe
dataframes
datasheet
datastore
datastores
datatype
datatypes
debounce
debounced
debouncing
debuggable
declaratively
decrypt
decrypted
decryption
deduplication
deepfake
deeplink
deeplinks
defrag
defragment
degoogle
deno
dep
deps
deserialize
deserialized
deserializer
devops
diffable
digitalocean
dirname
django
dll
dns
docker
dockerfile
dockerize
dockerized
dom
dotenv
dotfile
dotfiles
downvote
downvoted
dropdown
dropdowns
drupal
dynamodb
ebook
ebooks
ecommerce
edgecase
elasticsearch
emoji
emojis
encrypt
encrypted
encryption
endian
endpoint
endpoints
enum
enums
epub
erlang
eslint
ethereum
eval
eventsource
expr
extrapolate
fallback
fallbacks
favicon
feedback
filesystem
filesystems
fintech
firefox
firewall
firewalls
firmware
flatmap
flywheel
formatter
formatters
frontend
frontends
fullstack
func
funcs
gatekeeper
geofence
geofencing
geolocation
getters
gig
gigabit
gigabyte
gigabytes
gist
gists
gitbook
github
gitlab
gitops
globbing
gmail
golang
gpu
gpus
grafana
graphql
grayscale
greenfield
grep
grpc
gui
guis
guid
guids
gzip
gzipped
hackathon
hackathons
hadoop
hardcode
hardcoded
hardcoding
hashmap
hashmaps
hashtag
hashtags
hdfs
heartbleed
heroku
hexadecimal
homebrew
hostname
hostnames
hotfix
hotfixes
hotkey
hotkeys
hotspot
hotspots
href
html
http
https
hyperlink
hyperlinks
hypervisor
idempotent
idempotency
iframe
iframes
imagenet
inbox
incognito
infobox
infographic
infographics
infosec
init
inline
inlined
inlining
innersource
instanceof
internet
interop
interoperability
io
ios
iot
ip
ipc
iptables
ipv
isbn
iso
iterable
iterables
jailbreak
jailbreaking
jamstack
java
javascript
jenkins
jetbrains
jira
jpeg
jquery
json
jsonl
jsx
jupyter
jwt
kafka
kanban
kde
kebab
keybind
keybinding
keybindings
keychain
keymap
keymaps
keypress
keypresses
keystroke
keystrokes
keyvalue
kibana
kickback
kotlin
kubernetes
lambda
lambdas
lang
langs
latency
ldap
lerna
lifecycle
lifecycles
linter
linters
linting
linux
livereload
llm
llms
localhost
lockfile
logfile
logfiles
lookup
lookups
lossless
lossy
lua
lzma
macos
mailto
malware
mapreduce
markdown
memcached
metadata
microservice
microservices
middleware
middlewares
millis
millisecond
milliseconds
minified
minifier
minify
mixin
mixins
mmap
mockup
mockups
mongo
mongodb
monorepo
monorepos
multicast
multicore
multihop
multiline
multipart
multiplayer
multiplex
multiplexer
multiprocess
multiprocessing
multitenant
multitenancy
multithread
multithreaded
multithreading
mutex
mysql
namespace
namespaces
natively
navbar
navbars
netlify
netmask
nginx
nntp
nocache
nodejs
noop
noops
nosql
npm
nullable
numpad
nvme
oauth
observability
ocaml
offline
onclick
onprem
onpremise
opensource
openssl
oplog
orm
os
oss
outbox
overclock
overclocked
overclocking
pageview
pageviews
parallelism
param
params
parseable
passphrase
passphrases
passthrough
pathname
pathnames
payback
perf
permalink
permalinks
phishing
php
pixel
pixels
plaintext
playbook
playbooks
plugin
plugins
png
podcast
podcasts
polyfill
polyfills
popup
popups
portforward
portforwarding
postgres
postgresql
prebuilt
precache
precached
precompile
precompiled
precompute
precomputed
preconfig
preconfigured
prefetch
prefetched
preflight
preload
preloaded
preloading
preprocess
preprocessed
preprocessor
prerender
prerendered
prettify
profiler
profilers
programmatically
provisioner
provisioners
proxy
proxied
proxies
pseudocode
pubkey
pubsub
pulldown
pullrequest
pushback
pushdown
pytest
python
quantization
queryable
querier
quickstart
rabbitmq
rasterize
rasterized
readline
readonly
realtime
reauth
reauthenticate
rebalance
rebalanced
rebase
rebased
rebasing
recompile
recompiled
reconfiguration
reconfigure
reconfigured
redis
refactor
refactored
refactoring
refactors
regex
regexes
regexp
regexps
reindex
reindexed
remapper
renderer
renderers
repo
repos
requeue
requeued
resize
resized
resolver
resolvers
resp
revalidate
revalidated
rollback
rollbacks
roundtrip
roundtrips
rsync
ruby
runbook
runbooks
runtime
runtimes
rust
saas
sandboxed
scalability
scalable
screencast
screencasts
screenshot
screenshots
scss
sdk
sdks
serializable
serialization
serialize
serialized
serializer
serverless
serverside
servlet
servlets
setback
setbacks
setters
sha
sharding
shellcode
shim
shims
signin
signup
sitemap
sitemaps
sklearn
slack
slider
sliders
smtp
snackbar
snackbars
snippet
snippets
socket
sockets
solidity
sourcemap
sourcemaps
spam
spammer
spammers
splunk
sql
sqlite
ssd
ssh
ssl
stackoverflow
startup
startups
stderr
stdin
stdout
storefront
storefronts
stringified
stringify
subdirectory
subdomain
subdomains
subnet
subnets
subpath
subpaths
subprocess
subprocesses
subquery
subtask
subtasks
sudo
svg
svn
swappable
symlink
symlinks
sync
synced
syncing
sysadmin
syslog
tabindex
tagline
taglines
tcp
teardown
teardowns
techstack
telemetry
templated
terraform
textarea
textareas
thrash
threadpool
throughput
timestamp
timestamps
tls
tmpdir
todo
todos
tokenization
tokenize
tokenized
tokenizer
tooltip
tooltips
traceback
tracebacks
transpile
transpiled
transpiler
transpilers
truthy
tsx
tuple
tuples
tweakable
twilio
typescript
ubuntu
udp
uid
uids
uncomment
uncommented
undelete
undo
undos
unflag
unflagged
unicode
uninstall
uninstalled
uninstaller
unix
unlink
unlinked
unmerge
unmerged
unmount
unmounted
unpin
unpinned
unregister
unregistered
unserialize
unserialized
unsorted
unsubscribe
unsubscribed
untrusted
unversioned
unzip
unzipped
uptime
uri
uris
url
urls
usb
username
usernames
utf
uuid
uuids
validator
validators
vercel
versioned
versioning
vhost
vim
virtualization
virtualize
virtualized
vlan
vlans
vm
vms
vpc
vpcs
vpn
vpns
vscode
vuejs
wasm
webapp
webapps
webcam
webcams
webflow
webhook
webhooks
webmaster
webpack
webrtc
websocket
websockets
webview
webviews
whitelist
whitelisted
whitelisting
whitespace
widget
widgets
wifi
wiki
wikis
wildcard
wildcards
wordpress
workflow
workflows
workaround
workarounds
workload
workloads
workspace
workspaces
xpath
xss
yaml
youtube
zapier
zookeeper
`,Qs=3;let de=null,B=null,jt=!1,Vn=!1;async function ei(){const e=await import("harper.js"),n=new e.LocalLinter({binary:e.binary,dialect:e.Dialect.American});return await n.setup(),n}async function ni(){const e=await import("dictionary-en"),t=(await import("nspell")).default;let o;return typeof e.default=="function"?o=await new Promise((s,i)=>{e.default((r,a)=>{r?i(r):s(a)})}):o=e.default,new t(o.aff,o.dic)}async function Bt(){var t,o;const[e,n]=await Promise.allSettled([de??(de=ei()),B??(B=ni())]);e.status==="rejected"&&(console.warn("[GhostEdit] Harper init failed:",(t=e.reason)==null?void 0:t.message),de=null),n.status==="rejected"&&(console.warn("[GhostEdit] nspell init failed:",(o=n.reason)==null?void 0:o.message),B=null),!jt&&n.status==="fulfilled"&&ti(n.value),!Vn&&n.status==="fulfilled"&&Ht()}function ti(e){const n=Js.split(`
`).map(t=>t.trim()).filter(t=>t.length>0);for(const t of n)e.add(t);jt=!0}function Ht(){B&&B.then(e=>{const n=m.loadPersonalDictionary();for(const t of n)e.add(t);Vn=!0}).catch(()=>{})}function oi(){Vn=!1,B&&Ht()}function si(e){const t=e.lint_kind().toLowerCase();return t.includes("spell")||t.includes("mispell")?"spelling":t.includes("capitaliz")||t.includes("grammar")||t.includes("sentence")||t.includes("wrong")||t.includes("an_a")||t.includes("number")||t.includes("plural")||t.includes("tense")?"grammar":"style"}async function Kt(e,n){const t=await e.lint(n),o=[];for(const s of t){const i=s.span(),r=[];for(const a of s.suggestions())if(a.kind()===1)r.push("");else{const l=a.get_replacement_text();l!=null&&r.push(l)}r.length>0&&o.push({word:n.slice(i.start,i.end),range:{start:i.start,end:i.end},kind:si(s),suggestions:r,source:"harper"})}return o}const ii=["web","micro","multi","auto","pre","un","re","sub","super","over","under","cross","inter","semi","non","meta","pseudo","cyber","dev","push","pull","call","fall","feed","kick","set","pay","cut","drop","roll","back","down","out","up"];function Wt(e){return/^[a-z]+[A-Z]/.test(e)}function Vt(e){return/[a-zA-Z]/.test(e)&&/\d/.test(e)}function qt(e,n){const t=e.toLowerCase();for(const o of ii)if(t.startsWith(o)&&t.length>o.length){const s=t.slice(o.length);if(s.length>=3&&n.correct(s))return!0}return!1}function ri(e,n){return Wt(e)||Vt(e)||qt(e,n)}function Yt(e,n){const t=[],o=/[a-zA-Z'\u2019]+/g;let s;for(;(s=o.exec(n))!==null;){const i=s[0],r=s.index,a=r+i.length;if(!(i.length<=1)&&!/^['\u2019]+$/.test(i)&&!ri(i,e)&&!e.correct(i)){const l=e.suggest(i);l.length>0&&t.push({word:i,range:{start:r,end:a},kind:"spelling",suggestions:l.slice(0,5),source:"nspell"})}}return t}function Zt(e,n){const t=[...e];for(const o of n)e.some(i=>o.range.start<i.range.end&&o.range.end>i.range.start)||t.push(o);return t}function ai(e,n){return n.length===0?e:e.filter(t=>!n.some(o=>t.range.start<o.end&&t.range.end>o.start))}function Xt(e,n){return e.filter(t=>{if(t.kind!=="spelling")return!0;const o=t.word;if(/^[A-Z]{2,}$/.test(o))return!1;if(/^[A-Z][a-z]/.test(o)){const s=t.range.start;if(s===0)return!0;const i=n.slice(Math.max(0,s-3),s);if(!(/[.!?]\s+$/.test(i)||/^\s*$/.test(n.slice(0,s))))return!1}return!0})}function Jt(e,n,t){return e.filter(o=>{const s=/[a-zA-Z0-9]+/g;let i;for(;(i=s.exec(n))!==null;){const r=i.index,a=r+i[0].length;if(r<=o.range.start&&a>=o.range.end){const l=i[0];if(Wt(l)||Vt(l)||t&&qt(l,t))return!1;break}}return!0})}function li(e,n){const t=e.length,o=n.length,s=Array.from({length:o+1},(i,r)=>r);for(let i=1;i<=t;i++){let r=s[0];s[0]=i;for(let a=1;a<=o;a++){const l=s[a];s[a]=e[i-1]===n[a-1]?r:1+Math.min(r,s[a],s[a-1]),r=l}}return s[o]}function ci(e,n){const t=e.toLowerCase(),o=n.toLowerCase();if(t[0]!==o[0]&&t.length>1&&o.length>1&&t[1]!==o[1])return!1;const s=li(t,o),i=t.length<=6?2:t.length<=10?3:4;if(s>i)return!1;const r=t.length<8?2:3;return!(Math.abs(t.length-o.length)>r)}function qn(e,n){if(n.length===0)return{text:e,fixCount:0};const t=[...n].sort((i,r)=>r.range.start-i.range.start);let o=e,s=0;for(const i of t){const r=o.slice(i.range.start,i.range.end);if(r!==i.word)continue;const a=i.suggestions[0];a!==void 0&&a!==r&&(i.source==="nspell"&&!ci(i.word,a)||(o=o.slice(0,i.range.start)+a+o.slice(i.range.end),s++))}return{text:o,fixCount:s}}async function Qt(e,n){await Bt();const t=de?await de.catch(()=>null):null,o=B?await B.catch(()=>null):null;if(!t&&!o)return{text:e,issuesFixed:0,passes:0};let s=e,i=0,r=0;for(let a=0;a<Qs;a++){r++;const l=t?await Kt(t,s):[],d=o?Yt(o,s):[];let u=Zt(l,d);if(u=ai(u,n),u=Xt(u,s),u=Jt(u,s,o),u.length===0)break;const{text:p,fixCount:b}=qn(s,u);if(i+=b,b===0||p===s)break;s=p}return{text:s,issuesFixed:i,passes:r}}async function eo(e,n){return Qt(e,n)}async function di(e){await Bt();const n=de?await de.catch(()=>null):null,t=B?await B.catch(()=>null):null;if(!n&&!t)return[];const o=n?await Kt(n,e):[],s=t?Yt(t,e):[];let i=Zt(o,s);return i=Xt(i,e),i=Jt(i,e,t),i}async function no(e,n){return Qt(e,n)}function ui(e){c.ipcMain.handle(f.GET_CONFIG,()=>m.load()),c.ipcMain.handle(f.SAVE_CONFIG,async(n,t)=>{const o=m.load();return m.save(t),o.localModelVariant!==t.localModelVariant&&Ms(),(o.localModelEngine==="bonsai"&&t.localModelEngine!=="bonsai"||o.bonsaiModelSize!==t.bonsaiModelSize)&&await $t().catch(()=>{}),c.ipcMain.emit("config-changed"),{success:!0}}),c.ipcMain.handle(f.GET_CLI_STATUS,()=>{const n=m.load(),t={};for(const[o,s]of Object.entries(D)){const i=n[s.configPathKey]||void 0,r=gn(s.name,i);t[o]={found:!!r,path:r}}return t}),c.ipcMain.handle(f.CORRECT_TEXT,async(n,t,o)=>{try{const s=m.load();return{success:!0,...await ye(t,o,s)}}catch(s){return{success:!1,error:s}}}),c.ipcMain.handle(f.CORRECT_TEXT_STREAMING,async(n,t,o)=>{try{const s=m.load(),i=await Zs(t,o,r=>{n.sender.isDestroyed()||n.sender.send(f.STREAMING_CHUNK,r)},s);return n.sender.isDestroyed()||n.sender.send(f.STREAMING_DONE,i.text),{success:!0,...i}}catch(s){return n.sender.isDestroyed()||n.sender.send(f.STREAMING_ERROR,s),{success:!1,error:s}}}),c.ipcMain.handle(f.GET_HISTORY,()=>nt()),c.ipcMain.handle(f.CLEAR_HISTORY,()=>(ss(),{success:!0})),c.ipcMain.handle(f.OPEN_WINDOW,(n,t)=>(e(t),{success:!0})),c.ipcMain.handle(f.GET_LOCAL_MODEL_STATUS,()=>({engine:m.load().localModelEngine,t5:As(),bonsai:{models:ot(),server:st()}})),c.ipcMain.handle(f.GET_BONSAI_STATUS,()=>({models:ot(),server:st()})),c.ipcMain.handle(f.DOWNLOAD_BONSAI_MODEL,async(n,t)=>{try{return await $s(t,o=>{n.sender.isDestroyed()||n.sender.send(f.DOWNLOAD_BONSAI_PROGRESS,{size:t,progress:o})}),{success:!0}}catch(o){return n.sender.isDestroyed()||n.sender.send(f.DOWNLOAD_BONSAI_ERROR,{size:t,error:String(o)}),{success:!1,error:String(o)}}}),c.ipcMain.handle(f.GET_INFERENCE_DEVICE,()=>Un()),c.ipcMain.handle(f.DOWNLOAD_MODEL_VARIANT,async(n,t)=>{try{return await Os(t,o=>{n.sender.isDestroyed()||n.sender.send(f.DOWNLOAD_VARIANT_PROGRESS,{variant:t,progress:o})}),{success:!0}}catch(o){return n.sender.isDestroyed()||n.sender.send(f.DOWNLOAD_VARIANT_ERROR,{variant:t,error:String(o)}),{success:!1,error:String(o)}}}),c.ipcMain.handle(f.EXPORT_HISTORY,async(n,t)=>{const o=nt(),s=t==="json"?"json":"csv",i=await c.dialog.showSaveDialog({title:"Export Correction History",defaultPath:`ghostedit-history.${s}`,filters:[t==="json"?{name:"JSON",extensions:["json"]}:{name:"CSV",extensions:["csv"]}]});if(i.canceled||!i.filePath)return{success:!1};let r;if(t==="json")r=JSON.stringify(o,null,2);else{const a=`id,timestamp,originalText,generatedText,provider,model,durationMs,succeeded
`,l=o.map(d=>[d.id,d.timestamp,it(d.originalText),it(d.generatedText),d.provider,d.model,d.durationMilliseconds,d.succeeded].join(","));r=a+l.join(`
`)}return await h.promises.writeFile(i.filePath,r,"utf-8"),{success:!0,path:i.filePath}}),c.ipcMain.handle(f.GET_ERROR_LOG,()=>Xs()),c.ipcMain.handle(f.GET_SYSTEM_PROMPT,()=>{const t=m.load().localModelEngine==="bonsai"?$n:Pe;return{prompt:m.loadSystemPrompt(),defaultPrompt:t}}),c.ipcMain.handle(f.SAVE_SYSTEM_PROMPT,(n,t)=>(m.saveSystemPrompt(t),{success:!0})),c.ipcMain.handle(f.GET_PERSONAL_DICTIONARY,()=>m.loadPersonalDictionary()),c.ipcMain.handle(f.SAVE_PERSONAL_DICTIONARY,(n,t)=>(m.savePersonalDictionary(t),oi(),{success:!0})),c.ipcMain.handle(f.GET_USAGE_STATS,()=>as()),c.ipcMain.handle(f.RE_CORRECT,async(n,t)=>{try{const o=m.load(),s=await ye(m.loadSystemPrompt(),t,o);return{success:!0,text:s.text,durationMs:s.durationMs}}catch(o){return{success:!1,error:(o==null?void 0:o.message)||String(o)}}}),c.ipcMain.handle(f.EXPLAIN_DIFF,async(n,t,o)=>{try{const s=m.load(),i=`Explain in 10 words or fewer why "${t}" was changed to "${o}". Be specific about the grammar or spelling rule.`,r=s.localModelEngine==="bonsai"?`bonsai-${s.bonsaiModelSize}`:"t5-grammar";return{success:!0,explanation:(await ye(i,"",{...s,provider:s.provider==="local"?"local":s.cliProvider,model:s.provider==="local"?r:s.cliModel})).text}}catch{const s=t.toLowerCase(),i=o.toLowerCase();return s===i?{success:!0,explanation:"Capitalization fix"}:{success:!0,explanation:"Spelling or grammar correction"}}}),c.ipcMain.handle(f.CORRECT_INLINE,async(n,t)=>{try{const o=m.load(),s=o.localModelEngine==="bonsai"?`bonsai-${o.bonsaiModelSize}`:"t5-grammar";return{success:!0,text:(await ye("You are a grammar correction assistant. Fix grammar, spelling, and punctuation in the provided text. Return ONLY the corrected text, nothing else.",t,{...o,provider:"local",model:s})).text}}catch(o){return{success:!1,error:(o==null?void 0:o.message)||String(o)}}})}function it(e){return e.includes(",")||e.includes('"')||e.includes(`
`)?`"${e.replace(/"/g,'""')}"`:e}const pi="[K",fi="]",mi=[/`[^`\n]+`/g,/https?:\/\/[^\s<>()]+[^\s<>()\.,;:!?]/g,/[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}/g,/(?:~|\/|\.{1,2}\/)(?:[A-Za-z0-9._\-]+\/)*[A-Za-z0-9._\-]+(?:\.[A-Za-z0-9._\-]+)?/g,/(?:[A-Za-z0-9._\-]+\/){1,}[A-Za-z0-9._\-]+(?:\.[A-Za-z0-9._\-]+)?/g,/:[A-Za-z0-9_+\-]+:/g,/<!(?:here|channel|everyone)>/g,/<!subteam\^[^|>]+(?:\|[^>]+)?>/g,new RegExp("(?<![\\w@])@<[^>\\s]+>","g"),new RegExp("(?<![\\w@])<@[A-Za-z0-9][A-Za-z0-9._\\-]*>","g"),new RegExp("(?<![\\w@])@[A-Za-z0-9](?:[A-Za-z0-9._\\-]*[A-Za-z0-9_\\-])?","g"),new RegExp("(?<![#\\w])#[A-Za-z][A-Za-z0-9_\\-]*","g"),/\b[A-Z][A-Z0-9]+-\d+\b/g];function to(e){const n=[],t=[];let o=e;for(const s of mi){s.lastIndex=0;const i=[];let r;for(;(r=s.exec(o))!==null;){const a=r.index,l=a+r[0].length;t.some(u=>a<u.end&&l>u.start)||i.push({match:r[0],index:a})}if(i.length>0){i.sort((d,u)=>d.index-u.index);const a=[];let l=0;for(const{match:d,index:u}of i){const p=`${pi}${n.length}${fi}`;n.push({placeholder:p,originalToken:d}),a.push(o.slice(l,u)),a.push(p),t.push({start:u,end:u+p.length}),l=u+d.length}a.push(o.slice(l)),o=a.join("")}}return{protectedText:o,tokens:n,hasProtectedTokens:n.length>0}}function In(e,n){let t=e;for(let o=n.length-1;o>=0;o--){const{placeholder:s,originalToken:i}=n[o];t=t.replaceAll(s,i)}return t}function Rn(e,n){return n.every(t=>e.includes(t.placeholder))}function oo(e,n){return n.map(t=>{const o=e.indexOf(t.placeholder);return{start:o,end:o+t.placeholder.length}}).filter(t=>t.start>=0)}function Ln(e,n){let t=e;for(const{placeholder:o,originalToken:s}of n)t.includes(o)&&(t=t.replaceAll(o,s));return t}function so(e,n){const t=[];for(const{originalToken:o}of n){let s=0,i;for(;(i=e.indexOf(o,s))!==-1;)t.push({start:i,end:i+o.length}),s=i+o.length}return t}function io(e){return e.replace(/\[K\d+\]/g,"")}let xn=null,rt=null;function Yn(){if(!xn)try{const e=require("@nut-tree-fork/nut-js");xn=e.keyboard,rt=e.Key}catch(e){console.error("[GhostEdit] Failed to load @nut-tree-fork/nut-js:",e);const n=new Error(`Key simulation failed: ${(e==null?void 0:e.message)||e}`);throw n.cause=e,n}return{keyboard:xn,Key:rt}}function ro(){return{text:c.clipboard.readText()||"",html:c.clipboard.readHTML()||""}}function ao(e){e.html?c.clipboard.write({text:e.text,html:e.html}):c.clipboard.writeText(e.text)}function J(e){return new Promise(n=>setTimeout(n,e))}const wn=process.platform==="win32",un=wn?10:5,lo=wn?300:200,gi=wn?40:20,hi=wn?80:50;async function yi(){const{keyboard:e,Key:n}=Yn();c.clipboard.writeText("");const t=process.platform==="darwin"?n.LeftSuper:n.LeftControl;await e.pressKey(t,n.C),await e.releaseKey(t,n.C);let o=0,s="";for(;o<lo&&(await J(un),o+=un,s=c.clipboard.readText(),!s););if(!s)throw new Error("No text was captured. Make sure text is selected.");return s}async function ue(e){const{keyboard:n,Key:t}=Yn();c.clipboard.writeText(e),await J(gi);const o=process.platform==="darwin"?t.LeftSuper:t.LeftControl;await n.pressKey(o,t.V),await n.releaseKey(o,t.V),await J(hi)}async function Zn(){const{keyboard:e,Key:n}=Yn();c.clipboard.writeText(""),process.platform==="darwin"?(await e.pressKey(n.LeftSuper,n.Left),await e.releaseKey(n.LeftSuper,n.Left),await J(20),await e.pressKey(n.LeftSuper,n.LeftShift,n.Right),await e.releaseKey(n.LeftSuper,n.LeftShift,n.Right),await J(20),await e.pressKey(n.LeftSuper,n.C),await e.releaseKey(n.LeftSuper,n.C)):(await e.pressKey(n.Home),await e.releaseKey(n.Home),await J(20),await e.pressKey(n.LeftShift,n.End),await e.releaseKey(n.LeftShift,n.End),await J(20),await e.pressKey(n.LeftControl,n.C),await e.releaseKey(n.LeftControl,n.C));let t=0,o="";for(;t<lo&&(await J(un),t+=un,o=c.clipboard.readText(),!o););if(!o)throw new Error("No line text was captured. Make sure the cursor is in a text field.");return o}function we(e){c.clipboard.writeText(e)}const wi=100,be=new Map;function co(e,n,t,o,s){return`${n}:${t}:${o}:${s}:${e}`}function bi(e,n,t,o,s){return be.get(co(e,n,t,o,s))??null}function Si(e,n,t,o,s,i){const r=co(e,n,t,o,s);if(be.size>=wi){const a=be.keys().next().value;a&&be.delete(a)}be.set(r,i)}function Ti(){be.clear()}function Ei(e,n=!1){return uo(e,n).message}function uo(e,n=!1){var r;const t=e==null?void 0:e.type,o=m.load(),s=D[o.cliProvider];switch(t){case"cli-not-found":return{message:"CLI not found. Open Settings to set the path.",action:"open-settings",actionLabel:"Open Settings"};case"authentication-required":return{message:`Authentication needed. Run \`${(s==null?void 0:s.authCommand)??"auth"}\` in Terminal.`,action:"copy-command",actionLabel:"Copy Command",actionPayload:(s==null?void 0:s.authCommand)??"auth"};case"timed-out":return{message:"Timed out. Try increasing the timeout in Settings.",action:"open-settings",actionLabel:"Open Settings"};case"empty-response":return{message:"The AI returned nothing. Try again or switch providers.",action:null};case"process-failed":case"launch-failed":return{message:"Could not run the AI. Check CLI path in Settings.",action:"open-settings",actionLabel:"Open Settings"};case"protected-tokens-modified":return{message:"Some formatting was lost during correction. Please check the result.",action:null}}let i=(e==null?void 0:e.message)||String(e||"Correction failed");if(n){const a=(r=e==null?void 0:e.cause)!=null&&r.message?` [cause: ${e.cause.message}]`:"";i=i+a}else i.length>80&&(i=i.slice(0,77)+"...");return{message:i,action:null}}function pn(e){if(process.platform==="darwin")Ae.execFile("afplay",[e],n=>{n&&console.warn("[GhostEdit] Sound playback failed:",n.message)});else if(process.platform==="win32"){const n=e==="success"?"[System.Media.SystemSounds]::Asterisk.Play()":"[System.Media.SystemSounds]::Hand.Play()";Ae.execFile("powershell",["-NoProfile","-Command",n],t=>{t&&console.warn("[GhostEdit] Sound playback failed:",t.message)})}else{const n=e==="success"?"/usr/share/sounds/freedesktop/stereo/complete.oga":"/usr/share/sounds/freedesktop/stereo/dialog-error.oga";Ae.execFile("paplay",[n],t=>{t&&console.warn("[GhostEdit] Sound playback failed:",t.message)})}}function nn(){process.platform==="darwin"?pn("/System/Library/Sounds/Glass.aiff"):pn("success")}function po(){process.platform==="darwin"?pn("/System/Library/Sounds/Basso.aiff"):pn("error")}const at=500,fo=3e3;let Cn=null,Be=!1,C="",j=null,De=!1,mo=fo,Oe=null,Ie=null,Re=null,Le=null;const ki=new Map([[2,["1","!"]],[3,["2","@"]],[4,["3","#"]],[5,["4","$"]],[6,["5","%"]],[7,["6","^"]],[8,["7","&"]],[9,["8","*"]],[10,["9","("]],[11,["0",")"]],[30,["a","A"]],[48,["b","B"]],[46,["c","C"]],[32,["d","D"]],[18,["e","E"]],[33,["f","F"]],[34,["g","G"]],[35,["h","H"]],[23,["i","I"]],[36,["j","J"]],[37,["k","K"]],[38,["l","L"]],[50,["m","M"]],[49,["n","N"]],[24,["o","O"]],[25,["p","P"]],[16,["q","Q"]],[19,["r","R"]],[31,["s","S"]],[20,["t","T"]],[22,["u","U"]],[47,["v","V"]],[17,["w","W"]],[45,["x","X"]],[21,["y","Y"]],[44,["z","Z"]],[51,[";",":"]],[52,["'",'"']],[53,["`","~"]],[43,["\\","|"]],[39,[",","<"]],[40,[".",">"]],[41,["/","?"]],[12,["-","_"]],[13,["=","+"]],[26,["[","{"]],[27,["]","}"]]]),_i=57,vi=14,xi=83,Ci=28,Ai=15,Pi=203,Mi=205,Di=200,Oi=208,Ii=199,Ri=207,Li=1,Ni=2,Gi=8;function go(){if(!Cn)try{Cn=require("uiohook-napi").uIOhook}catch(e){throw console.error("[GhostEdit] Failed to load uiohook-napi:",e.message),e}return Cn}function ho(e){const n=e.keycode,t=!!(e.shiftKey||e.mask&&e.mask&1),o=!!(e.ctrlKey||e.mask&&e.mask&Ni),s=!!(e.metaKey||e.mask&&e.mask&Gi);if(o||s){(n===30||n===44||n===47)&&(C="",G());return}if(n===Pi||n===Mi||n===Di||n===Oi||n===Ii||n===Ri||n===Li){C="",G();return}if(Fi(),n===vi){C.length>0&&(C=C.slice(0,-1),G());return}if(n===xi){C="",G();return}if(n===Ci){t?(C+=`
`,Je(),G()):(C="",G());return}if(n===Ai){C+="	",Je(),G();return}if(n===_i){C+=" ",Je(),G();return}const r=ki.get(n);r&&(C+=t?r[1]:r[0],Je(),G())}function Je(){C.length>at&&(C=C.slice(C.length-at))}function Fi(){De||(De=!0,Ie==null||Ie()),j&&clearTimeout(j),j=setTimeout(()=>{De=!1,Re==null||Re(),j=null},mo)}function G(){Oe==null||Oe(C)}function yo(){Le==null||Le()}function $i(e,n){if(!Be){Oe=e.onBufferChange,Ie=e.onTypingStarted,Re=e.onTypingStopped,Le=e.onMouseClick??null,mo=n??fo;try{const t=go();t.on("keydown",ho),t.on("mousedown",yo),t.start(),Be=!0,console.log("[GhostEdit] Keystroke monitoring started")}catch(t){console.error("[GhostEdit] Could not start keystroke monitoring:",t)}}}function zi(){if(Be){try{const e=go();e.removeListener("keydown",ho),e.removeListener("mousedown",yo),e.stop()}catch{}j&&(clearTimeout(j),j=null),Be=!1,De=!1,C="",Oe=null,Ie=null,Re=null,Le=null,console.log("[GhostEdit] Keystroke monitoring stopped")}}function Xn(){C="",G()}function Ui(){C="",De=!1,j&&(clearTimeout(j),j=null),G()}function ji(){return Be}let Y=null,Ne=null,Ge=!1,He=!1,fn=null;function Nn(e){for(const n of[" - "," | "," — "]){const t=e.indexOf(n);if(t>0)return e.slice(0,t).trim()}return e.trim()}function Bi(e,n){return Nn(e)===Nn(n)}function wo(e){const n=e.toLowerCase();return n.includes("ghostedit")||n.includes("ghost edit")}async function bo(){if(!fn)return null;try{return(await fn()).title??null}catch{return null}}function Hi(e){Ne=e.onAppSwitch,Y=null,Ge=!1,He=!1;try{fn=require("@nut-tree-fork/nut-js").getActiveWindow,console.log("[GhostEdit] App context tracker initialized")}catch(n){console.warn("[GhostEdit] Could not load nut-js for app context tracking:",n.message),He=!0}}async function Ki(){if(He||Y!==null)return;const e=await bo();e&&!wo(e)&&(Y=e)}async function lt(){if(!(He||!Y||Ge)){Ge=!0;try{const e=await bo();if(!e||wo(e))return;Bi(e,Y)||Ne==null||Ne()}finally{Ge=!1}}}function ct(){Y=null}function Gn(){return Y?Nn(Y):null}function Wi(){Y=null,Ne=null,Ge=!1,He=!1,fn=null}const Vi=300,qi=3;let q=null,ne=null,pe=[],z="green",tn=!1,I=null,R=null;function Yi(e){I=e.onColorChange,R=e.onIssuesChange,pe=[],z="green"}function Zi(){q&&clearTimeout(q),ne&&clearTimeout(ne),q=null,ne=null,I=null,R=null,pe=[],z="green",tn=!1}function Xi(e){q&&clearTimeout(q),ne&&clearTimeout(ne);const n=m.load();if(n.meetingModeEnabled){const t=Gn(),o=n.meetingApps??[];if(t&&o.some(s=>t.toLowerCase().includes(s.toLowerCase()))){z!=="green"&&(z="green",pe=[],I==null||I("green"),R==null||R([]));return}}if(n.monitoringAppFilter==="whitelist"){const t=Gn(),o=n.monitoringAppWhitelist??[];if(t&&o.length>0&&!o.some(s=>t.toLowerCase().includes(s.toLowerCase()))){z!=="green"&&(z="green",pe=[],I==null||I("green"),R==null||R([]));return}}if(e.trim().length<qi){z!=="green"&&(z="green",pe=[],I==null||I("green"),R==null||R([]));return}q=setTimeout(()=>{Ji(e)},Vi)}async function Ji(e){if(!tn){tn=!0;try{let n=await di(e);const o=m.load().suppressedSuggestions??{};n=n.filter(i=>(o[i.word]??0)<2),pe=n;const s=Qi(n);z=s,I==null||I(s),R==null||R(n)}catch(n){console.error("[GhostEdit] Realtime analysis error:",n)}finally{tn=!1}}}function Qi(e){return e.length===0?"green":e.some(t=>t.kind==="spelling"||t.kind==="grammar")?"red":"yellow"}function bn(){pe=[],z="green",q&&clearTimeout(q),ne&&clearTimeout(ne),q=null,ne=null}let T=null,_=[],dt=!1;function er(){return g.join(__dirname,"../preload/index.js")}function nr(e){return`file://${g.join(__dirname,"../renderer/main_window/index.html")}?windowType=${e}`}function tr(){const e=ms();if(e&&e.width>0&&e.height>0)return process.platform!=="win32"?{x:Math.round(e.x+e.width/2-320/2),y:e.y+e.height+4}:{x:Math.round(e.x+e.width/2-320/2),y:e.y-300-4};const n=c.screen.getCursorScreenPoint(),t=c.screen.getDisplayNearestPoint(n),{x:o,y:s,width:i}=t.workArea;return{x:o+i-320-16,y:s+8}}function or(){dt||(dt=!0,c.ipcMain.handle(f.APPLY_FIX,async(e,n,t)=>(await dr(n,t),{success:!0})),c.ipcMain.handle(f.APPLY_ALL_FIXES,async()=>(await ur(),{success:!0})),c.ipcMain.handle(f.DISMISS_SUGGESTION,async(e,n)=>(await cr(n),{success:!0})),c.ipcMain.handle(f.CHECK_ACCESSIBILITY,()=>{if(process.platform==="darwin")try{const{systemPreferences:e}=require("electron");return{trusted:e.isTrustedAccessibilityClient(!1)}}catch{return{trusted:!1}}return{trusted:!0}}))}function sr(){or()}function Sn(e){cn(e)}function ir(e){_=e,vt(e.length),T&&!T.isDestroyed()&&T.isVisible()&&T.webContents.send(f.SUGGESTIONS_UPDATE,e)}function rr(e){if(_=e,T&&!T.isDestroyed()){T.webContents.send(f.SUGGESTIONS_UPDATE,e),T.isVisible()||T.show(),T.focus();return}const n=tr(),t=new c.BrowserWindow({width:320,height:300,x:n.x,y:n.y,show:!1,frame:!1,transparent:!0,alwaysOnTop:!0,skipTaskbar:!0,focusable:!0,resizable:!1,hasShadow:!0,webPreferences:{preload:er(),contextIsolation:!0,nodeIntegration:!1,sandbox:!0,backgroundThrottling:!1}});t.loadURL(nr("suggestions")).catch(s=>{console.error("[GhostEdit] Failed to load suggestions dropdown:",s.message)});const o=()=>{t.webContents.send(f.SUGGESTIONS_UPDATE,e),t.show(),t.focus()};t.webContents.isLoading()?t.webContents.once("did-finish-load",o):t.once("ready-to-show",o),t.on("blur",()=>{setTimeout(()=>{t&&!t.isDestroyed()&&t.hide()},150)}),t.on("closed",()=>{T=null}),T=t}function ar(){_.length>0&&rr(_)}function ut(){T&&!T.isDestroyed()&&(T.close(),T=null)}function lr(){T&&!T.isDestroyed()&&(T.close(),T=null),_=[],cn(null)}async function cr(e){if(e<0||e>=_.length)return;const n=_[e],t=m.load(),o={...t.suppressedSuggestions??{}};o[n.word]=(o[n.word]??0)+1,m.save({...t,suppressedSuggestions:o}),_=_.filter((i,r)=>r!==e),T&&!T.isDestroyed()&&T.webContents.send(f.SUGGESTIONS_UPDATE,_);const s=_.length===0?"green":_.some(i=>i.kind==="spelling"||i.kind==="grammar")?"red":"yellow";Sn(s),vt(_.length)}async function dr(e,n){if(!(e<0||e>=_.length))try{const t=await Zn(),o=_[e],s=n!=null&&n>0&&n<o.suggestions.length?{...o,suggestions:[o.suggestions[n],...o.suggestions.filter((a,l)=>l!==n)]}:o,i=qn(t,[s]);i.fixCount>0&&await ue(i.text),_=_.filter((a,l)=>l!==e),Xn(),bn(),T&&!T.isDestroyed()&&T.webContents.send(f.SUGGESTIONS_UPDATE,_);const r=_.length===0?"green":_.some(a=>a.kind==="spelling"||a.kind==="grammar")?"red":"yellow";Sn(r)}catch(t){console.error("[GhostEdit] Failed to apply single fix:",t)}}async function ur(){if(_.length!==0)try{const e=await Zn(),n=qn(e,_);n.fixCount>0&&await ue(n.text),_=[],Xn(),bn(),T&&!T.isDestroyed()&&T.webContents.send(f.SUGGESTIONS_UPDATE,[]),Sn("green")}catch(e){console.error("[GhostEdit] Failed to apply all fixes:",e)}}const pr=c.app.requestSingleInstanceLock();pr?c.app.on("second-instance",()=>{ae("settings")}):c.app.quit();const An=new Map;function Jn(){return g.join(__dirname,"../preload/index.js")}function Qn(e){return`file://${g.join(__dirname,"../renderer/main_window/index.html")}?windowType=${e}`}function ae(e){const n=An.get(e);if(n&&!n.isDestroyed())return n.show(),n.focus(),n;const o={settings:{width:680,height:520},history:{width:700,height:500},hud:{width:300,height:80},"streaming-preview":{width:700,height:400},suggestions:{width:320,height:300}}[e],s=e==="hud",i=e==="streaming-preview",r=new c.BrowserWindow({width:o.width,height:o.height,show:!1,frame:!s&&!i,transparent:s||i,alwaysOnTop:s||i,skipTaskbar:s,focusable:!s,resizable:!s,hasShadow:!s,...s||i?{}:{titleBarStyle:"hiddenInset"},...process.platform==="darwin"&&!s&&!i?{vibrancy:"under-window"}:{},webPreferences:{preload:Jn(),contextIsolation:!0,nodeIntegration:!1,sandbox:!0,backgroundThrottling:s?!1:void 0}});return r.loadURL(Qn(e)).catch(a=>{console.error(`[GhostEdit] Failed to load window "${e}":`,a.message)}),r.once("ready-to-show",()=>{s||r.show()}),r.on("closed",()=>{An.delete(e)}),An.set(e,r),r}let W=null;function fr(){if(W&&!W.isDestroyed())return W;const e=new c.BrowserWindow({width:300,height:80,show:!1,frame:!1,transparent:!0,alwaysOnTop:!0,skipTaskbar:!0,focusable:!1,resizable:!1,hasShadow:!1,webPreferences:{preload:Jn(),contextIsolation:!0,nodeIntegration:!1,sandbox:!0,backgroundThrottling:!1}});return e.loadURL(Qn("hud")).catch(n=>{console.error("[GhostEdit] Failed to load HUD:",n.message)}),W=e,e}let Se=null,Fe=null;function N(e,n=2e3){Se&&clearTimeout(Se),Fe&&clearTimeout(Fe);const t=fr(),o=c.screen.getCursorScreenPoint(),s=c.screen.getDisplayNearestPoint(o),{x:i,y:r,width:a,height:l}=s.workArea;t.setPosition(Math.round(i+a/2-150),Math.round(r+l*.15));const d=()=>{t.webContents.send(f.HUD_SHOW,e),t.isVisible()||t.showInactive()};t.webContents.isLoading()?t.webContents.once("did-finish-load",d):d(),Se=setTimeout(()=>{t&&!t.isDestroyed()&&(t.webContents.send(f.HUD_HIDE),Fe=setTimeout(()=>{t&&!t.isDestroyed()&&(t.close(),W=null)},300)),Se=null},n)}function pt(){Se&&clearTimeout(Se),Fe&&clearTimeout(Fe),W&&!W.isDestroyed()&&(W.close(),W=null)}let K=null,$e=null;function mr(){K&&!K.isDestroyed()&&(K.close(),K=null),$e&&(clearTimeout($e),$e=null);const e=c.screen.getCursorScreenPoint(),n=c.screen.getDisplayNearestPoint(e),{x:t,y:o,width:s,height:i}=n.workArea,r=new c.BrowserWindow({width:700,height:400,x:Math.round(t+s/2-350),y:Math.round(o+i/2-200),show:!1,frame:!1,transparent:!0,alwaysOnTop:!0,skipTaskbar:!0,focusable:!1,resizable:!1,hasShadow:!1,webPreferences:{preload:Jn(),contextIsolation:!0,nodeIntegration:!1,sandbox:!0,backgroundThrottling:!1}});return r.loadURL(Qn("streaming-preview")).catch(a=>{console.error("[GhostEdit] Failed to load passive preview:",a.message)}),K=r,r}function on(){const e=m.load(),{streakDates:n}=Tt(e.streakDates??[]);m.save({...e,streakDates:n})}const ft=5,ze=[];function Pn(e,n){ze.unshift({original:e,corrected:n,timestamp:Date.now()}),ze.length>ft&&(ze.length=ft)}function gr(){return ze}let Te=!1,U=null;async function se(e,n){if(Te)return;Te=!0,ln("processing");const t=m.load(),o=e?{...t,provider:e,model:n??(e==="local"?t.localModelEngine==="bonsai"?`bonsai-${t.bonsaiModelSize}`:"t5-grammar":t.model)}:t,s=Date.now();let i=null,r="";try{N("Working..."),i=ro(),r=await yi();let a=m.loadSystemPrompt();const l=Gn(),d=l&&t.appToneOverrides[l]?t.appToneOverrides[l]:t.tonePreset,u=yt[d];u&&(a=u),t.language&&t.language!=="auto"&&(a+=`

Respond in ${t.language}.`);const p=to(r),b=oo(p.protectedText,p.tokens),E=(await eo(p.protectedText,b)).text,x=bi(E,o.provider,o.model,t.tonePreset,t.language);let w;if(x)w=x.text,p.hasProtectedTokens&&(Rn(x.text,p.tokens)?w=In(x.text,p.tokens):w=Ln(x.text,p.tokens));else{const y=await ye(a,E,o);Si(E,o.provider,o.model,t.tonePreset,t.language,y),p.hasProtectedTokens?Rn(y.text,p.tokens)?w=In(y.text,p.tokens):w=Ln(y.text,p.tokens):w=y.text;const A=p.hasProtectedTokens?so(w,p.tokens):[];w=(await no(w,A)).text}if(w=io(w),t.diffPreviewMode==="interactive"){pt();const y=ae("streaming-preview");await new Promise(k=>{y.webContents.isLoading()?y.webContents.once("did-finish-load",()=>k()):k()}),await new Promise(k=>setTimeout(k,150)),y.webContents.send(f.SET_PREVIEW_ORIGINAL,r),y.webContents.send(f.STREAMING_DONE,w),y.webContents.send(f.SET_PREVIEW_CONFIG,{autoPasteDelaySeconds:t.autoPasteDelaySeconds,diffPreviewMode:"interactive",passivePreviewSeconds:0});const A=await new Promise(k=>{U={resolve:k},y.on("closed",()=>{U&&(U.resolve(!1),U=null)})});y.isDestroyed()||y.close(),A&&(process.platform==="darwin"&&(c.app.hide(),await new Promise(k=>setTimeout(k,150))),t.clipboardOnlyMode?we(w):await ue(w),Pn(r,w),t.soundFeedbackEnabled&&nn(),t.notifyOnSuccess&&new c.Notification({title:"GhostEdit",body:"Correction applied."}).show());const v={id:he.randomUUID(),timestamp:new Date().toISOString(),originalText:r,generatedText:w,provider:o.provider,model:o.model,durationMilliseconds:Date.now()-s,succeeded:A,rejected:!A};xe(v,t.historyLimit),A&&on()}else if(t.diffPreviewMode==="passive"){pt(),t.clipboardOnlyMode?we(w):await ue(w),Pn(r,w),t.soundFeedbackEnabled&&nn(),t.notifyOnSuccess&&new c.Notification({title:"GhostEdit",body:"Correction applied."}).show();const y=mr(),A=()=>{setTimeout(()=>{y.webContents.send(f.SET_PREVIEW_ORIGINAL,r),y.webContents.send(f.STREAMING_DONE,w),y.webContents.send(f.SET_PREVIEW_CONFIG,{autoPasteDelaySeconds:0,diffPreviewMode:"passive",passivePreviewSeconds:t.passivePreviewSeconds}),y.showInactive()},150)};y.webContents.isLoading()?y.webContents.once("did-finish-load",A):A(),$e=setTimeout(()=>{K&&!K.isDestroyed()&&(K.close(),K=null),$e=null},t.passivePreviewSeconds*1e3);const v={id:he.randomUUID(),timestamp:new Date().toISOString(),originalText:r,generatedText:w,provider:o.provider,model:o.model,durationMilliseconds:Date.now()-s,succeeded:!0};xe(v,t.historyLimit),on()}else{t.clipboardOnlyMode?(we(w),N("Copied to clipboard!")):(await ue(w),N("Done!")),Pn(r,w),t.soundFeedbackEnabled&&nn(),t.notifyOnSuccess&&new c.Notification({title:"GhostEdit",body:"Correction applied."}).show();const y={id:he.randomUUID(),timestamp:new Date().toISOString(),originalText:r,generatedText:w,provider:o.provider,model:o.model,durationMilliseconds:Date.now()-s,succeeded:!0};xe(y,t.historyLimit),on()}}catch(a){const l=uo(a,t.developerMode);console.error("Correction error:",a),l.action?(N(`Error: ${l.message}`,15e3),l.action==="open-settings"?setTimeout(()=>ae("settings"),200):l.action==="copy-command"&&l.actionPayload&&we(l.actionPayload)):N(`Error: ${l.message}`,t.developerMode?8e3:5e3),t.soundFeedbackEnabled&&po(),Ut(l.message,o.provider),new c.Notification({title:"GhostEdit",body:l.message}).show();const d={id:he.randomUUID(),timestamp:new Date().toISOString(),originalText:r,generatedText:"",provider:o.provider,model:o.model,durationMilliseconds:Date.now()-s,succeeded:!1};xe(d,t.historyLimit)}finally{i&&!t.clipboardOnlyMode&&setTimeout(()=>{i&&ao(i)},2e3),ln("idle"),Te=!1}}async function Mn(){const e=is();if(!e){N("Nothing to undo");return}m.load().clipboardOnlyMode?(we(e.originalText),N("Original text copied to clipboard")):(await ue(e.originalText),N("Undo: original text restored"))}async function mt(){if(Te)return;Te=!0,ln("processing");const e=m.load(),n=Date.now();let t=null,o="";try{N("Working..."),t=ro(),o=await Zn();let s=m.loadSystemPrompt();const i=yt[e.tonePreset];i&&(s=i),e.language&&e.language!=="auto"&&(s+=`

Respond in ${e.language}.`);const r=to(o),a=oo(r.protectedText,r.tokens),d=(await eo(r.protectedText,a)).text,u=await ye(s,d,e);let p;r.hasProtectedTokens?Rn(u.text,r.tokens)?p=In(u.text,r.tokens):p=Ln(u.text,r.tokens):p=u.text;const b=r.hasProtectedTokens?so(p,r.tokens):[];p=(await no(p,b)).text,p=io(p),e.clipboardOnlyMode?(we(p),N("Copied to clipboard!")):(await ue(p),N("Done!")),e.soundFeedbackEnabled&&nn();const E={id:he.randomUUID(),timestamp:new Date().toISOString(),originalText:o,generatedText:p,provider:e.provider,model:e.model,durationMilliseconds:Date.now()-n,succeeded:!0};xe(E,e.historyLimit),on(),Xn(),bn()}catch(s){const i=Ei(s,e.developerMode);console.error("Line correction error:",s),N(`Error: ${i}`,e.developerMode?8e3:5e3),e.soundFeedbackEnabled&&po(),Ut(i,e.provider)}finally{t&&!e.clipboardOnlyMode&&setTimeout(()=>{t&&ao(t)},2e3),ln("idle"),Te=!1}}function So(){const e=m.load();if(e.monitoringEnabled&&!ji()){if(process.platform==="darwin")try{const{systemPreferences:n}=require("electron");if(!n.isTrustedAccessibilityClient(!1)){console.warn("[GhostEdit] Accessibility not granted — monitoring disabled"),c.dialog.showMessageBox({type:"warning",title:"Accessibility Permission Required",message:"GhostEdit needs Accessibility permission to monitor your typing.",detail:"Open System Settings > Privacy & Security > Accessibility and add GhostEdit. Then restart the app.",buttons:["Open System Settings","Later"],defaultId:0,cancelId:1}).then(t=>{t.response===0&&c.shell.openExternal("x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility")});return}}catch{}sr(),Yi({onColorChange:n=>{Sn(n)},onIssuesChange:n=>{ir(n)}}),Hi({onAppSwitch:()=>{Ui(),bn(),cn(null),ut(),ct()}}),$i({onBufferChange:n=>{Xi(n),n.length===0&&(cn(null),ut(),ct())},onTypingStarted:()=>{Ki()},onTypingStopped:()=>{lt()},onMouseClick:()=>{lt()}},e.trafficLightInactivityMs),console.log("[GhostEdit] Real-time monitoring started")}}function To(){zi(),Zi(),lr(),Wi(),console.log("[GhostEdit] Real-time monitoring stopped")}function hr(){To(),So()}var gt;process.platform==="darwin"&&((gt=c.app.dock)==null||gt.hide());c.app.whenReady().then(()=>{console.log("[GhostEdit] App ready"),m.ensureDefaults(),ui(ae),c.ipcMain.on("window-close",o=>{var s;(s=c.BrowserWindow.fromWebContents(o.sender))==null||s.close()}),c.ipcMain.on("window-minimize",o=>{var s;(s=c.BrowserWindow.fromWebContents(o.sender))==null||s.minimize()}),c.ipcMain.handle(f.ACCEPT_CORRECTION,async(o,s)=>(U&&(U.resolve(!0),U=null),{success:!0})),c.ipcMain.handle(f.REJECT_CORRECTION,()=>(U&&(U.resolve(!1),U=null),{success:!0})),c.ipcMain.handle(f.REGENERATE_CORRECTION,async()=>(se(),{success:!0}));const e={onCorrectLocal:()=>se("local"),onCorrectCLI:()=>{const o=m.load();se(o.cliProvider,o.cliModel)},onUndoLastCorrection:()=>Mn(),onOpenSettings:()=>ae("settings"),onOpenHistory:()=>ae("history"),onShowSuggestions:()=>ar(),onDownloadUpdate:()=>cs(),getRecentCorrections:()=>ze};gs(e),ls({onUpdateAvailable:()=>{dn(e)}}),Mt(()=>se("local"),()=>{const o=m.load();se(o.cliProvider,o.cliModel)},()=>Mn(),()=>mt()),So(),setTimeout(()=>{const o=m.load();o.provider==="local"&&o.localModelEngine==="bonsai"?Wn(o.bonsaiModelSize).catch(s=>{console.warn("[GhostEdit] Bonsai pre-warm failed:",s.message)}):Is()},3e3),c.ipcMain.on("config-changed",()=>{m.invalidateCache(),Ti(),Qo();const o=m.load();c.app.setLoginItemSettings({openAtLogin:o.launchAtLogin}),dn(e),ws(()=>se("local"),()=>{const s=m.load();se(s.cliProvider,s.cliModel)},()=>Mn(),()=>mt()),hr()});const n=m.load();c.app.setLoginItemSettings({openAtLogin:n.launchAtLogin});let t="";setInterval(()=>{if(!m.load().dailyDigestEnabled)return;const s=new Date().toISOString().split("T")[0];if(t===s)return;const i=rs();if(i.count===0)return;const r=`Today: ${i.count} correction${i.count===1?"":"s"}. ${i.successRate}% success rate.`;new c.Notification({title:"GhostEdit Daily Digest",body:r}).show(),t=s},3600*1e3),n.firstRunComplete||ae("settings"),console.log("[GhostEdit] Startup complete")}).catch(e=>{console.error("[GhostEdit] Fatal error:",e)});c.app.on("will-quit",()=>{Dt(),ys(),To(),Ws()});c.app.on("window-all-closed",()=>{});exports.getRecentCorrections=gr;
