name: GhostEdit
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    MACOSX_DEPLOYMENT_TARGET: 13.0
targets:
  GhostEditCore:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: GhostEdit/Sources
        excludes:
          - main.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ghostedit.core
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        SKIP_INSTALL: YES
  GhostEdit:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: GhostEdit/Sources/main.swift
    resources:
      - path: GhostEdit/Assets.xcassets
    dependencies:
      - target: GhostEditCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ghostedit.app
        INFOPLIST_FILE: GhostEdit/Info.plist
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.1
        ENABLE_HARDENED_RUNTIME: YES
  GhostEditTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: GhostEditTests
    dependencies:
      - target: GhostEditCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ghostedit.tests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        TEST_HOST: ""
        BUNDLE_LOADER: ""
schemes:
  GhostEdit:
    build:
      targets:
        GhostEditCore: all
        GhostEdit: all
    test:
      targets:
        - name: GhostEditTests
    run:
      config: Debug
  GhostEditTests:
    build:
      targets:
        GhostEditCore: all
        GhostEditTests: all
    test:
      targets:
        - name: GhostEditTests
