name: GhostEdit
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    MACOSX_DEPLOYMENT_TARGET: 13.0
    GCC_TREAT_WARNINGS_AS_ERRORS: YES
targets:
  GhostEditCore:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: GhostEdit/Sources
        excludes:
          - main.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ghostedit.core
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        SKIP_INSTALL: YES
        SWIFT_INCLUDE_PATHS: $(SRCROOT)/build/harper
        LIBRARY_SEARCH_PATHS: $(SRCROOT)/build/harper
        OTHER_LDFLAGS: -lharper_bridge
  GhostEdit:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: GhostEdit/Sources/main.swift
      - path: GhostEdit/Assets.xcassets
        buildPhase: resources
      - path: GhostEdit/Resources
        buildPhase: resources
    dependencies:
      - target: GhostEditCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ghostedit.app
        INFOPLIST_FILE: GhostEdit/Info.plist
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 37
        MARKETING_VERSION: 7.7.0
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_INCLUDE_PATHS: $(SRCROOT)/build/harper
        LIBRARY_SEARCH_PATHS: $(SRCROOT)/build/harper
        OTHER_LDFLAGS: -lharper_bridge
  GhostEditTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: GhostEditTests
    dependencies:
      - target: GhostEditCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ghostedit.tests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        TEST_HOST: ""
        BUNDLE_LOADER: ""
        SWIFT_INCLUDE_PATHS: $(SRCROOT)/build/harper
        LIBRARY_SEARCH_PATHS: $(SRCROOT)/build/harper
        OTHER_LDFLAGS: -lharper_bridge
schemes:
  GhostEdit:
    build:
      targets:
        GhostEditCore: all
        GhostEdit: all
    test:
      targets:
        - name: GhostEditTests
    run:
      config: Debug
  GhostEditTests:
    build:
      targets:
        GhostEditCore: all
        GhostEditTests: all
    test:
      targets:
        - name: GhostEditTests
